In [260]:
import kagglehub
import pandas as pd
import ast
import numpy as np

In [261]:
path = kagglehub.dataset_download(
    "rounakbanik/the-movies-dataset"
)
metaDataDF = pd.read_csv(f"{path}/movies_metadata.csv")
ratingsDF = pd.read_csv(f"{path}/ratings.csv")
linksDF = pd.read_csv(f"{path}/links.csv")
creditsDF = pd.read_csv(f"{path}/credits.csv")
keywordsDF = pd.read_csv(f"{path}/keywords.csv")
links_smallDF = pd.read_csv(f"{path}/links_small.csv")
ratings_smallDF = pd.read_csv(f"{path}/ratings_small.csv")

C:\Users\Taha Riyaan\AppData\Local\Temp\ipykernel_22612\2128828587.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  metaDataDF = pd.read_csv(f"{path}/movies_metadata.csv")

# Dataset - The Movies Dataset by Rounak Banik
report by John Lopes & Taha Riyaan

## Description

"About Dataset
Context
These files contain metadata for all 45,000 movies listed in the Full MovieLens Dataset. The dataset consists of movies released on or before July 2017. Data points include cast, crew, plot keywords, budget, revenue, posters, release dates, languages, production companies, countries, TMDB vote counts and vote averages.

This dataset also has files containing 26 million ratings from 270,000 users for all 45,000 movies. Ratings are on a scale of 1-5 and have been obtained from the official GroupLens website.

Content
This dataset consists of the following files:

movies_metadata.csv: The main Movies Metadata file. Contains information on 45,000 movies featured in the Full MovieLens dataset. Features include posters, backdrops, budget, revenue, release dates, languages, production countries and companies.

keywords.csv: Contains the movie plot keywords for our MovieLens movies. Available in the form of a stringified JSON Object.

credits.csv: Consists of Cast and Crew Information for all our movies. Available in the form of a stringified JSON Object.

links.csv: The file that contains the TMDB and IMDB IDs of all the movies featured in the Full MovieLens dataset.

links_small.csv: Contains the TMDB and IMDB IDs of a small subset of 9,000 movies of the Full Dataset.

ratings_small.csv: The subset of 100,000 ratings from 700 users on 9,000 movies.

The Full MovieLens Dataset consisting of 26 million ratings and 750,000 tag applications from 270,000 users on all the 45,000 movies in this dataset can be accessed here

Acknowledgements
This dataset is an ensemble of data collected from TMDB and GroupLens.
The Movie Details, Credits and Keywords have been collected from the TMDB Open API. This product uses the TMDb API but is not endorsed or certified by TMDb. Their API also provides access to data on many additional movies, actors and actresses, crew members, and TV shows. You can try it for yourself here.

The Movie Links and Ratings have been obtained from the Official GroupLens website. The files are a part of the dataset available here



Inspiration
This dataset was assembled as part of my second Capstone Project for Springboard's Data Science Career Track. I wanted to perform an extensive EDA on Movie Data to narrate the history and the story of Cinema and use this metadata in combination with MovieLens ratings to build various types of Recommender Systems.

Both my notebooks are available as kernels with this dataset: The Story of Film and Movie Recommender Systems

Some of the things you can do with this dataset:
Predicting movie revenue and/or movie success based on a certain metric. What movies tend to get higher vote counts and vote averages on TMDB? Building Content Based and Collaborative Filtering Based Recommendation Engines."

We decided to go with this dataset because we enjoying watching movies

# Code

## Functions

In [262]:
# def check_json_columns_for_null(df, columns):
#     for col in columns:
#         if col not in df.columns:
#             continue
            
#         print(f" === Auditing Column: {col} === ")
        
#         # 1: Standard Nulls 
#         standard_nulls = df[col].isnull().sum()
        
#         # 2: Empty List Strings
#         empty_lists = (df[col] == '[]').sum()
        
#         # 3: String '[null]' 
#         string_nulls = (df[col] == '[null]').sum()
        
#         # 4: Empty strings or whitespace
#         # empty_strings = (df[col].str.strip() == '').sum() if df[col].dtype == 'object' else 0
#         empty_strings = (df[col].str.strip() == '').sum()


#         print(f"Standard NaNs Count: {standard_nulls}")
#         print(f"Empty List '[]' Count: {empty_lists}")
#         print(f"String '[null]' Count: {string_nulls}")
#         print(f"Empty Strings Count: {empty_strings}")
        
#         # 5: Check for corrupted text instead of JSON
#         try:
#             sample_val = df[col].dropna().iloc[0]
#             ast.literal_eval(sample_val)
#             print(f"Valid JSON.")
#         except Exception as e:
#             print(f"Corrupted JSON.")
        
#         print("\n")

In [263]:
def json_to_dict(x):
    if pd.isna(x) or x == '':
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return None

In [264]:
def json_to_list(x):
    # genres, production_companies, production_countries, spoken_languages
    
    if pd.isna(x) or x == "" or x == "[]":
        return []
    try:
        genres = ast.literal_eval(x)
        return [g['name'] for g in genres]
    except:
        return []

# df['genres'] = df['genres'].apply(extract_genres)

In [265]:

def json_to_list_cred(x):
    # creditsDF: crew, cast
    if pd.isna(x) or x == "" or x == "[]":
        return []
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return []

## `2. Prepare the Data`

### Basic Info

#### `movie_metadata`

In [266]:
print(' === movie_metadata Information === ')
metaDataDF.info()

print('\n === movie_metadata Shape === ')
print(metaDataDF.shape)

 === movie_metadata Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

 === movie_metadata Shape ===
(45466, 24)

In [267]:
print('\n === movie_metadata Head === ')
print(metaDataDF.head(5))

 === movie_metadata Head ===
   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
2  A family wedding reignites the ancient feud be...  ...   1995-12-22
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4  Just when George Banks has recovered from his ...  ...   1995-02-10

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

[5 rows x 24 columns]

In [268]:
# Columns in terms of appropriate dtype

metadata_float_cols = ['popularity', 'revenue', 'runtime', 'vote_average', 'vote_count']
metadata_int_cols = ['budget', 'id']
metadata_string_cols = [
    'homepage', 
    'imdb_id', 
    'original_language', 
    'original_title',
    'overview',
    'poster_path',
    'status',
    'tagline',
    'title'
    ]
metadata_dict_cols = ['belongs_to_collection']
metadata_list_cols = [
    'genres',
    'production_companies',
    'production_countries',
    'spoken_languages'
    ]
metadata_bool_cols = ['adult', 'video']
metadata_datetime_cols = ['release_date']

In [269]:
# Convert columns from object to appropriate dtype
import pandas as pd

metadata_converted_DF = metaDataDF.copy()

# float
for col in metadata_float_cols:
    metadata_converted_DF[col] = pd.to_numeric(metaDataDF[col], errors='coerce').astype('float64')

# int
for col in metadata_int_cols:
    metadata_converted_DF[col] = pd.to_numeric(metaDataDF[col], errors='coerce').astype('Int64')

# # string
# for col in metadata_string_cols:
#     metadata_converted_DF[col] = metaDataDF[col].astype('string')

# bool
for col in metadata_bool_cols:
    # handle cases like 'True'/'False' or 1/0
    metadata_converted_DF[col] = metaDataDF[col].map({
        True: True, False: False,
        'True': True, 'False': False,
        1: True, 0: False
    }).astype('boolean')

# date time
for col in metadata_datetime_cols:
    metadata_converted_DF[col] = pd.to_datetime(metaDataDF[col], errors='coerce')

# dict
for col in metadata_dict_cols:
    metadata_converted_DF[col] = metaDataDF[col].apply(json_to_dict)

# list
for col in metadata_list_cols:
    metadata_converted_DF[col] = metaDataDF[col].apply(json_to_list)

# verify
print(metadata_converted_DF.dtypes)

adult                           boolean
belongs_to_collection            object
budget                            Int64
genres                           object
homepage                         object
id                                Int64
imdb_id                          object
original_language                object
original_title                   object
overview                         object
popularity                      float64
poster_path                      object
production_companies             object
production_countries             object
release_date             datetime64[ns]
revenue                         float64
runtime                         float64
spoken_languages                 object
status                           object
tagline                          object
title                            object
video                           boolean
vote_average                    float64
vote_count                      float64
dtype: object

In [270]:
print('\n === movie_metadata Number of Missing Values === ')
print(metadata_converted_DF.isna().sum())

 === movie_metadata Number of Missing Values ===
adult                        3
belongs_to_collection    40972
budget                       3
genres                       0
homepage                 37684
id                           3
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   6
poster_path                386
production_companies         0
production_countries         0
release_date                90
revenue                      6
runtime                    263
spoken_languages             0
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [271]:
# clean movie_metadata
from sklearn.impute import SimpleImputer
metadata_clean = metadata_converted_DF.copy()

median_imp = SimpleImputer(missing_values=np.nan, strategy='median')

print('=== Cleaning movie_metadata -> dealing with null values ===')


# ids -> can not merge on certain tables without valid ID
# Will not recommend movie without name
# Will not recommend unreleased movie
# revenue, budget, video,  -> drop, assume movie never made it
drop = [
    'id', 
    'imdb_id', 
    'title', 
    'release_date',
    'revenue',
    'budget',
    'video'
]
print(f"== Drop following values: {', '.join(map(str, drop))} ==")
metadata_clean = metadata_clean.dropna(subset=drop)
print(f"success")

# runtime -> median run time imputation
print('== Run Median Imputation on Runtime ==')
metadata_clean['runtime'] = median_imp.fit_transform(metadata_clean[['runtime']])
print(f"success")

# popularity, vote_average, vote_count ->
# impute with 0
fill_0 = ['popularity', 'vote_average', 'vote_count']
print(f"== Impute following values with 0 {', '.join(map(str, fill_0))} ==")
metadata_clean[fill_0] = metadata_clean[fill_0].fillna(0)
print(f"success")


# production_companies, production_countries, spoken_languages 
# genres->
# impute with empty list []
fill_list = [
    'production_companies', 
    'production_countries', 
    'spoken_languages', 
    'genres', 
]
print(f"== Impute following values with [] {', '.join(map(str, fill_list))} ==")
metadata_clean[fill_list] = metadata_clean[fill_list].fillna('[]')
print(f"success")

# belongs_to_collection -> fill with "No Collection"
print('== fill belongs_to_collection with "No Collection"')
metadata_clean['belongs_to_collection'] = metadata_clean['belongs_to_collection'].fillna("No Collection")
print(f"success")


# original_language -> impute with mode, English
print(f"== Impute following values using mode: original_language ==")
metadata_clean['original_language'] = metadata_clean['original_language'].fillna(
    metadata_clean['original_language'].mode()[0]
)
print(f"success")

# status -> fill with "Unknown"
print('== fill status with "Unknown"')
metadata_clean['status'] = metadata_clean['status'].fillna("Unknown")
print(f"success")


# homepage, tagline, poster_path -> drop, no analytical value
print('== Drop rows with no analytical value for future tasks: hompage, tagline, poster_path')
metadata_clean = metadata_clean.drop(columns=['homepage', 'tagline', 'poster_path'])
print(f"success")

# overview -> fill with empty string
print('== fill overview with ""')
metadata_clean['overview'] = metadata_clean['overview'].fillna("")
print(f"success")

=== Cleaning movie_metadata -> dealing with null values ===
== Drop following values: id, imdb_id, title, release_date, revenue, budget, video ==
success
== Run Median Imputation on Runtime ==
success
== Impute following values with 0 popularity, vote_average, vote_count ==
success
== Impute following values with [] production_companies, production_countries, spoken_languages, genres ==
success
== fill belongs_to_collection with "No Collection"
success
== Impute following values using mode: original_language ==
success
== fill status with "Unknown"
success
== Drop rows with no analytical value for future tasks: hompage, tagline, poster_path
success
== fill overview with ""
success

In [272]:
print('\n === movie_metadata Number of Missing Values Check === ')
print(metadata_clean.isna().sum())

 === movie_metadata Number of Missing Values Check ===
adult                    0
belongs_to_collection    0
budget                   0
genres                   0
id                       0
imdb_id                  0
original_language        0
original_title           0
overview                 0
popularity               0
production_companies     0
production_countries     0
release_date             0
revenue                  0
runtime                  0
spoken_languages         0
status                   0
title                    0
video                    0
vote_average             0
vote_count               0
dtype: int64

#### `ratings & ratings_small`

In [322]:
print(' === ratings Information === ')
ratingsDF.info()

print('\n === ratings Shape === ')
print(ratingsDF.shape)

 === ratings Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB

 === ratings Shape ===
(26024289, 4)

In [323]:
print(' === ratings_small Information === ')
ratings_smallDF.info()

print('\n === ratings_small Shape === ')
print(ratings_smallDF.shape)

 === ratings_small Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100004 entries, 0 to 100003
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100004 non-null  int64
 1   movieId    100004 non-null  int64
 2   rating     100004 non-null  float64
 3   timestamp  100004 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

 === ratings_small Shape ===
(100004, 4)

In [324]:
print('\n === ratings Head === ')
print(ratingsDF.head(5))

 === ratings Head ===
   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [325]:
print('\n === ratings_small Head === ')
print(ratings_smallDF.head(5))

 === ratings_small Head ===
   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [326]:
# Columns in terms of appropriate dtype

ratings_float_cols = ['rating']
ratings_int_cols = ['userId', 'movieId']

In [327]:
# Convert columns from object to appropriate dtype
import pandas as pd

ratings_converted_DF = ratingsDF.copy()
ratings_small_converted_DF = ratings_smallDF.copy()


# float
for col in ratings_float_cols:
    ratings_converted_DF[col] = pd.to_numeric(ratingsDF[col], errors='coerce').astype('float64')
    ratings_small_converted_DF[col] = pd.to_numeric(ratings_smallDF[col], errors='coerce').astype('float64')


# int
for col in ratings_int_cols:
    ratings_converted_DF[col] = pd.to_numeric(ratingsDF[col], errors='coerce').astype('Int64')
    ratings_small_converted_DF[col] = pd.to_numeric(ratings_smallDF[col], errors='coerce').astype('Int64')

print("=== ratings data types ===")
print(ratings_converted_DF.dtypes)

print("=== ratings_small data types ===")
print(ratings_small_converted_DF.dtypes)

=== ratings data types ===
userId         Int64
movieId        Int64
rating       float64
timestamp      int64
dtype: object
=== ratings_small data types ===
userId         Int64
movieId        Int64
rating       float64
timestamp      int64
dtype: object

In [328]:
print('\n === ratings_converted Number of Missing Values === ')
print(ratings_converted_DF.isna().sum())

print('\n === ratings_small Number of Missing Values === ')
print(ratings_small_converted_DF.isna().sum())

 === ratings_converted Number of Missing Values ===
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

 === ratings_small Number of Missing Values ===
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [329]:
# clean ratings

# run filter to conly keep rows where movieId exists in metadata_clean['id']
print('Dropping rows with no movieId that matches an id in metadata_clean')
ratings_clean = ratings_converted_DF[ratings_converted_DF['movieId'].isin(metadata_clean['id'])]

print(f"Ratings remaining: {len(ratings_clean)}")

# run filter to conly keep rows where movieId exists in metadata_clean['id']
print('Dropping rows in ratings_small with no movieId that matches an id in metadata_clean')
ratings_small_clean = ratings_small_converted_DF[ratings_small_converted_DF['movieId'].isin(metadata_clean['id'])]

print(f"Ratings remaining: {len(ratings_small_clean)}")

Dropping rows with no movieId that matches an id in metadata_clean
Ratings remaining: 11429489
Dropping rows in ratings_small with no movieId that matches an id in metadata_clean
Ratings remaining: 44960

In [330]:
print('\n === ratings Number of Missing Values Check === ')
print(ratings_clean.isna().sum())

print('\n === ratings_small Number of Missing Values Check === ')
print(ratings_small_clean.isna().sum())

 === ratings Number of Missing Values Check ===
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

 === ratings_small Number of Missing Values Check ===
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

#### `links & links_small`

In [282]:
print('\n === links Head === ')
print(linksDF.head(5))

 === links Head ===
   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [283]:
print('\n === links_small Head === ')
print(links_smallDF.head(5))

 === links_small Head ===
   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [284]:
# Columns in terms of appropriate dtype

links_int_cols = ['movieId', 'imdbId', 'tmdbId']

In [285]:
# Convert columns from object to appropriate dtype
import pandas as pd

links_converted_DF = linksDF.copy()
links_small_converted_DF = links_smallDF.copy()

# int
for col in links_int_cols:
    links_converted_DF[col] = pd.to_numeric(linksDF[col], errors='coerce').astype('Int64')
    links_small_converted_DF[col] = pd.to_numeric(links_smallDF[col], errors='coerce').astype('Int64')

print("=== ratings data types ===")
print(ratings_converted_DF.dtypes)

print("=== ratings_small data types ===")
print(ratings_small_converted_DF.dtypes)

=== ratings data types ===
userId         Int64
movieId        Int64
rating       float64
timestamp      int64
dtype: object
=== ratings_small data types ===
userId         Int64
movieId        Int64
rating       float64
timestamp      int64
dtype: object

In [286]:
print('\n === links_converted Number of Missing Values === ')
print(links_converted_DF.isna().sum())

print('\n === links_small Number of Missing Values === ')
print(links_small_converted_DF.isna().sum())

 === links_converted Number of Missing Values ===
movieId      0
imdbId       0
tmdbId     219
dtype: int64

 === links_small Number of Missing Values ===
movieId     0
imdbId      0
tmdbId     13
dtype: int64

In [287]:
# clean links

# run filter to only keep rows where movieId exists in metadata_clean['id']
print('Dropping rows with no movieId that matches an id in metadata_clean')
links_clean = links_converted_DF[links_converted_DF['movieId'].isin(metadata_clean['id'])]

print(f"links remaining: {len(links_clean)}")

Dropping rows with no movieId that matches an id in metadata_clean
links remaining: 7626

#### `Credits`

In [288]:
print(' === credits Information === ')
creditsDF.info()

print('\n === credits Shape === ')
print(creditsDF.shape)

 === credits Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

 === credits Shape ===
(45476, 3)

In [289]:
print('\n === credits Head === ')
print(creditsDF.head(5))

 === credits Head ===
                                                cast  \
0  [{'cast_id': 14, 'character': 'Woody (voice)',...
1  [{'cast_id': 1, 'character': 'Alan Parrish', '...
2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...
3  [{'cast_id': 1, 'character': "Savannah 'Vannah...
4  [{'cast_id': 1, 'character': 'George Banks', '...

                                                crew     id
0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...    862
1  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...   8844
2  [{'credit_id': '52fe466a9251416c75077a89', 'de...  15602
3  [{'credit_id': '52fe44779251416c91011acb', 'de...  31357
4  [{'credit_id': '52fe44959251416c75039ed7', 'de...  11862

In [290]:
# Columns in terms of appropriate dtype

credits_int_cols = ['id']
credits_list_cols = [
    'crew',
    'cast',
    ]

In [291]:
credits_converted_DF = creditsDF.copy()

# int
for col in credits_int_cols:
    credits_converted_DF[col] = pd.to_numeric(creditsDF[col], errors='coerce').astype('Int64')

# list
for col in credits_list_cols:
    credits_converted_DF[col] = creditsDF[col].apply(json_to_list_cred)

# verify
print(credits_converted_DF.dtypes)

cast    object
crew    object
id       Int64
dtype: object

In [292]:
print('\n === credits Number of Missing Values === ')
print(credits_converted_DF.isna().sum())

 === credits Number of Missing Values ===
cast    0
crew    0
id      0
dtype: int64

In [293]:
credits_converted_DF.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [294]:
# clean credits

# run filter to only keep rows where id exists in metadata_clean['id']
print('Dropping rows with no movieId that matches an id in metadata_clean')
credits_clean = credits_converted_DF[credits_converted_DF['id'].isin(metadata_clean['id'])]

print(f"Credits remaining: {len(credits_clean)}")

Dropping rows with no movieId that matches an id in metadata_clean
Credits remaining: 45375

#### `keywords`

In [295]:
print(' === keywords Information === ')
keywordsDF.info()

print('\n === keywords Shape === ')
print(keywordsDF.shape)

 === keywords Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

 === keywords Shape ===
(46419, 2)

In [296]:
print('\n === keywords Head === ')
print(ratingsDF.head(5))

 === keywords Head ===
   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [297]:
# Columns in terms of appropriate dtype

keywords_int_cols = ['id']
keywords_list_cols = [
    'keywords',
    ]

In [307]:
keywords_converted_DF = keywordsDF.copy()

# int
for col in keywords_int_cols:
    keywords_converted_DF[col] = pd.to_numeric(keywordsDF[col], errors='coerce').astype('Int64')

# list
for col in keywords_list_cols:
    keywords_converted_DF[col] = keywordsDF[col].apply(json_to_list)

# verify
print(keywords_converted_DF.dtypes)

id           Int64
keywords    object
dtype: object

In [308]:
print('\n === keywords Number of Missing Values === ')
print(keywords_converted_DF.isna().sum())

 === keywords Number of Missing Values ===
id          0
keywords    0
dtype: int64

In [309]:
keywords_converted_DF.head()

      id                                           keywords
0    862  [jealousy, toy, boy, friendship, friends, riva...
1   8844  [board game, disappearance, based on children'...
2  15602  [fishing, best friend, duringcreditsstinger, o...
3  31357  [based on novel, interracial relationship, sin...
4  11862  [baby, midlife crisis, confidence, aging, daug...

In [310]:
# clean keywords

# run filter to only keep rows where id exists in metadata_clean['id']
print('Dropping rows with no movieId that matches an id in metadata_clean')
keywords_clean = keywords_converted_DF[keywords_converted_DF['id'].isin(metadata_clean['id'])]

print(f"keywords remaining: {len(keywords_clean)}")

Dropping rows with no movieId that matches an id in metadata_clean
keywords remaining: 46317

### `Dictionary Cleaning`

#### `movie_metadata`

In [319]:
def belongs_to_coll_dict(x):
    if isinstance(x, dict):
        return True, x.get('id'), x.get('name')
    return False, None, None

In [321]:
"""
Flatten the dictionaries in belongs_to_collection ->
    belongs_to_collection: contains T/F
    collection_id: contains collection id
    collection_name: contains collection name

poster_path and backdrop dropped due to lack of analytical value

"""

metadata_clean[['belongs_to_collection', 'collection_id', 'collection_name']] = \
    metadata_clean['belongs_to_collection'].apply(belongs_to_coll_dict).apply(pd.Series)

print(metadata_clean.head())

   adult  belongs_to_collection    budget                        genres  \
0  False                   True  30000000   [Animation, Comedy, Family]
1  False                  False  65000000  [Adventure, Fantasy, Family]
2  False                   True         0             [Romance, Comedy]
3  False                  False  16000000      [Comedy, Drama, Romance]
4  False                   True         0                      [Comedy]

      id    imdb_id original_language               original_title  \
0    862  tt0114709                en                    Toy Story
1   8844  tt0113497                en                      Jumanji
2  15602  tt0113228                en             Grumpier Old Men
3  31357  tt0114885                en            Waiting to Exhale
4  11862  tt0113041                en  Father of the Bride Part II

                                            overview  popularity  ...  \
0  Led by Woody, Andy's toys live happily in his ...   21.946943  ...
1  When siblings Judy and Peter discover an encha...   17.015539  ...
2  A family wedding reignites the ancient feud be...   11.712900  ...
3  Cheated on, mistreated and stepped on, the wom...    3.859495  ...
4  Just when George Banks has recovered from his ...    8.387519  ...

       revenue runtime     spoken_languages    status  \
0  373554033.0    81.0            [English]  Released
1  262797249.0   104.0  [English, Français]  Released
2          0.0   101.0            [English]  Released
3   81452156.0   127.0            [English]  Released
4   76578911.0   106.0            [English]  Released

                         title  video vote_average vote_count  collection_id  \
0                    Toy Story  False          7.7     5415.0        10194.0
1                      Jumanji  False          6.9     2413.0            NaN
2             Grumpier Old Men  False          6.5       92.0       119050.0
3            Waiting to Exhale  False          6.1       34.0            NaN
4  Father of the Bride Part II  False          5.7      173.0        96871.0

                  collection_name
0            Toy Story Collection
1                            None
2       Grumpy Old Men Collection
3                            None
4  Father of the Bride Collection

[5 rows x 23 columns]

### Study 1

subset = genres, is_adult, runtime, x, x

Jaccard

Hamming

Cosine

### Study 2

### Study 3

## References