In [2]:
import kagglehub
import pandas as pd
import numpy as np
import ast

In [3]:
path = kagglehub.dataset_download(
    "rounakbanik/the-movies-dataset"
)
metaDataDF = pd.read_csv(f"{path}/movies_metadata.csv")
ratingsDF = pd.read_csv(f"{path}/ratings_small.csv")

C:\Users\Johnny\AppData\Local\Temp\ipykernel_25524\3779643782.py:4: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  metaDataDF = pd.read_csv(f"{path}/movies_metadata.csv")

# Dataset - The Movies Dataset by Rounak Banik
report by John Lopes & Taha Riyaan

## Description

"About Dataset
Context
These files contain metadata for all 45,000 movies listed in the Full MovieLens Dataset. The dataset consists of movies released on or before July 2017. Data points include cast, crew, plot keywords, budget, revenue, posters, release dates, languages, production companies, countries, TMDB vote counts and vote averages.

This dataset also has files containing 26 million ratings from 270,000 users for all 45,000 movies. Ratings are on a scale of 1-5 and have been obtained from the official GroupLens website.

Content
This dataset consists of the following files:

movies_metadata.csv: The main Movies Metadata file. Contains information on 45,000 movies featured in the Full MovieLens dataset. Features include posters, backdrops, budget, revenue, release dates, languages, production countries and companies.

keywords.csv: Contains the movie plot keywords for our MovieLens movies. Available in the form of a stringified JSON Object.

credits.csv: Consists of Cast and Crew Information for all our movies. Available in the form of a stringified JSON Object.

links.csv: The file that contains the TMDB and IMDB IDs of all the movies featured in the Full MovieLens dataset.

links_small.csv: Contains the TMDB and IMDB IDs of a small subset of 9,000 movies of the Full Dataset.

ratings_small.csv: The subset of 100,000 ratings from 700 users on 9,000 movies.

The Full MovieLens Dataset consisting of 26 million ratings and 750,000 tag applications from 270,000 users on all the 45,000 movies in this dataset can be accessed here

Acknowledgements
This dataset is an ensemble of data collected from TMDB and GroupLens.
The Movie Details, Credits and Keywords have been collected from the TMDB Open API. This product uses the TMDb API but is not endorsed or certified by TMDb. Their API also provides access to data on many additional movies, actors and actresses, crew members, and TV shows. You can try it for yourself here.

The Movie Links and Ratings have been obtained from the Official GroupLens website. The files are a part of the dataset available here



Inspiration
This dataset was assembled as part of my second Capstone Project for Springboard's Data Science Career Track. I wanted to perform an extensive EDA on Movie Data to narrate the history and the story of Cinema and use this metadata in combination with MovieLens ratings to build various types of Recommender Systems.

Both my notebooks are available as kernels with this dataset: The Story of Film and Movie Recommender Systems

Some of the things you can do with this dataset:
Predicting movie revenue and/or movie success based on a certain metric. What movies tend to get higher vote counts and vote averages on TMDB? Building Content Based and Collaborative Filtering Based Recommendation Engines."

We decided to go with this dataset because we enjoying watching movies

## Code

### Cleaning

### Study 1

subset = genres, revenue, runtime, production_companies, title

Jaccard

In [3]:
def extractGenreNames(genres):
    if pd.isna(genres):
        return set()
    if isinstance(genres, str):
        try:
            genres = ast.literal_eval(genres)
        except (ValueError, SyntaxError):
            return set()
    if isinstance(genres, list):
        return {item['name'] for item in genres if isinstance(item, dict) and 'name' in item}
    return set()

def jaccardSimilarity(a, b):
    if not a and not b:
        return 1.0
    union = a | b
    return len(a & b) / len(union) if union else 0.0

movie = "Minions"
movieName = movie.lower()

movieRow = metaDataDF[metaDataDF['title'].str.lower() == movieName]
if movieRow.empty:
    movieRow = metaDataDF[metaDataDF['original_title'].str.lower() == movieName]

movieGenres = extractGenreNames(movieRow.iloc[0]['genres']) if not movieRow.empty else set()
print(movie + " genres: " + str(movieGenres))

jaccardScores = []
for title in metaDataDF['title']:
    movieRow = metaDataDF[metaDataDF['title'] == title]
    if movieRow.empty:
        movieRow = metaDataDF[metaDataDF['original_title'] == title]
    genres = extractGenreNames(movieRow.iloc[0]['genres']) if not movieRow.empty else set()
    jaccardScores.append({
        'title': title,
        'genres': genres,
        'jaccard_similarity': jaccardSimilarity(movieGenres, genres),
    })

jaccardDF = pd.DataFrame(jaccardScores).sort_values('jaccard_similarity', ascending=False)
jaccardDF = jaccardDF[jaccardDF['title'] != movie]
jaccardDF.head(10)

Minions genres: {'Comedy', 'Family', 'Adventure', 'Animation'}

,title,genres,jaccard_similarity
8610,Asterix the Gaul,"{Comedy, Family, Adventure, Animation}",1.0
8626,Asterix and Cleopatra,"{Comedy, Family, Adventure, Animation}",1.0
43156,Smurfs: The Lost Village,"{Adventure, Family, Comedy, Animation}",1.0
608,The Aristocats,"{Family, Comedy, Adventure, Animation}",1.0
41586,Tri bogatyrya i Shamakhanskaya tsaritsa,"{Family, Comedy, Adventure, Animation}",1.0
40608,Storks,"{Adventure, Family, Comedy, Animation}",1.0
39750,VeggieTales: Tomato Sawyer & Huckleberry Larry...,"{Family, Comedy, Adventure, Animation}",1.0
39734,VeggieTales: Dave and the Giant Pickle,"{Adventure, Family, Comedy, Animation}",1.0
43294,Cars 3,"{Family, Comedy, Adventure, Animation}",1.0
39334,Ice Age: Collision Course,"{Adventure, Family, Comedy, Animation}",1.0

In [4]:
def extractCompanyNames(companies):
    if pd.isna(companies):
        return set()
    if isinstance(companies, str):
        try:
            companies = ast.literal_eval(companies)
        except (ValueError, SyntaxError):
            return set()
    if isinstance(companies, list):
        return {item['name'] for item in companies if isinstance(item, dict) and 'name' in item}
    return set()

movie = "Pocahontas"
movieName = movie.lower()

movieRow = metaDataDF[metaDataDF['title'].str.lower() == movieName]
if movieRow.empty:
    movieRow = metaDataDF[metaDataDF['original_title'].str.lower() == movieName]

movieCompanies = extractCompanyNames(movieRow.iloc[0]['production_companies']) if not movieRow.empty else set()
print(movie + " production companies: " + str(movieCompanies))

jaccardScores = []
for title in metaDataDF['title']:
    movieRow = metaDataDF[metaDataDF['title'] == title]
    if movieRow.empty:
        movieRow = metaDataDF[metaDataDF['original_title'] == title]
    companies = extractCompanyNames(movieRow.iloc[0]['production_companies']) if not movieRow.empty else set()
    jaccardScores.append({
        'title': title,
        'companies': companies,
        'jaccard_similarity': jaccardSimilarity(movieCompanies, companies),
    })

jaccardDF = pd.DataFrame(jaccardScores).sort_values('jaccard_similarity', ascending=False)
jaccardDF = jaccardDF[jaccardDF['title'] != movie]
jaccardDF.head(10)

Pocahontas production companies: {'Walt Disney Pictures', 'Walt Disney Feature Animation'}

,title,companies,jaccard_similarity
1798,Mulan,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
5744,Treasure Planet,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
10520,Chicken Little,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
359,The Lion King,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
4238,Atlantis: The Lost Empire,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
5310,Lilo & Stitch,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
3493,Dinosaur,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
3891,The Emperor's New Groove,"{Walt Disney Pictures, Walt Disney Feature Ani...",1.000000
1980,The Rescuers Down Under,"{Walt Disney Pictures, Silver Screen Partners ...",0.666667
1520,Air Bud,{Walt Disney Pictures},0.500000

Manhattan

In [5]:
movie = "Mortal Kombat"
movieName = movie.lower()

movieRow = metaDataDF[metaDataDF['title'].str.lower() == movieName]
if movieRow.empty:
    movieRow = metaDataDF[metaDataDF['original_title'].str.lower() == movieName]

movieRevenue = movieRow.iloc[0]['revenue'] if not movieRow.empty else 0.0
print(movie + " revenue: " + str(movieRevenue))

manhattanDistances = []
for i, row in metaDataDF.iterrows():
    rev = row['revenue']
    if pd.isna(rev) or pd.isna(movieRevenue):
        dist = float('inf')
    else:
        dist = abs(rev - movieRevenue)
    manhattanDistances.append({
        'title': row['title'],
        'revenue': rev,
        'manhattan_distance': dist,
    })

manhattanDF = pd.DataFrame(manhattanDistances)
manhattanDF = manhattanDF[manhattanDF['title'] != movie]
manhattanDF = manhattanDF.sort_values('manhattan_distance')
manhattanDF.head(10)

Mortal Kombat revenue: 122195920.0

                                  title      revenue  manhattan_distance
1885                        Poltergeist  122200000.0              4080.0
14494                          Invictus  122233971.0             38051.0
21604                         Prisoners  122126687.0             69233.0
7011                          Peter Pan  121975011.0            220909.0
1631                          MouseHunt  122417389.0            221469.0
489                  Executive Decision  121969216.0            226704.0
14234                        Surrogates  122444772.0            248852.0
10762                      Nanny McPhee  122489822.0            293902.0
31322                    Magic Mike XXL  122513057.0            317137.0
5255   Spirit: Stallion of the Cimarron  122563539.0            367619.0

Euclidean

In [6]:
movie = "Avatar"
movieName = movie.lower()

movieRow = metaDataDF[metaDataDF['title'].str.lower() == movieName]
if movieRow.empty:
    movieRow = metaDataDF[metaDataDF['original_title'].str.lower() == movieName]

movieRuntime = movieRow.iloc[0]['runtime'] if not movieRow.empty else 0.0
print(movie + " runtime: " + str(movieRuntime))

euclideanDistances = []
for i, row in metaDataDF.iterrows():
    rt = row['runtime']
    if pd.isna(rt) or pd.isna(movieRuntime):
        dist = float('inf')
    else:
        dist = np.sqrt((rt - movieRuntime) ** 2)
    euclideanDistances.append({
        'title': row['title'],
        'runtime': rt,
        'euclidean_distance': dist,
    })

euclideanDF = pd.DataFrame(euclideanDistances)
euclideanDF = euclideanDF[euclideanDF['title'] != movie]
euclideanDF = euclideanDF.sort_values('euclidean_distance')
euclideanDF.head(10)

Avatar runtime: 162.0

                                      title  runtime  euclidean_distance
38801                          Toni Erdmann    162.0                 0.0
14992                       Bunty Aur Babli    162.0                 0.0
18451  The Disappearance of Haruhi Suzumiya    162.0                 0.0
36560                Garv: Pride and Honour    162.0                 0.0
33610               Times of Joy and Sorrow    162.0                 0.0
29622                             Sarfarosh    162.0                 0.0
33434                  A Tale of Two Cities    162.0                 0.0
12520                      Marketa Lazarová    162.0                 0.0
7934                   How the West Was Won    162.0                 0.0
36571                                 Rakht    162.0                 0.0

Edit Distance

In [ ]:
def levenshtein(s1, s2):
    if len(s1) < len(s2):
        return levenshtein(s2, s1)
    if len(s2) == 0:
        return len(s1)
    previousRow = list(range(len(s2) + 1))
    for i, c1 in enumerate(s1):
        currentRow = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previousRow[j + 1] + 1
            deletions = currentRow[j] + 1
            substitutions = previousRow[j] + (c1 != c2)
            currentRow.append(min(insertions, deletions, substitutions))
        previousRow = currentRow
    return previousRow[-1]

movie = "Pacific Rum"
editDistances = []
for title in metaDataDF['title']:
    dist = levenshtein(movie, str(title))
    editDistances.append({
        'title': title,
        'edit_distance': dist,
    })

editDF = pd.DataFrame(editDistances).sort_values('edit_distance')
editDF.head(10)

                title  edit_distance
21123     Pacific Rim              1
5132       Panic Room              5
26192       Sacrifice              6
38348       Sacrifice              6
18385       Sacrifice              6
40995  Pacific Banana              6
30770     Traffic Jam              6
9239          Mimic 2              7
11792      Maniac Cop              7
35942           Panic              7

### Study 2

### Study 3

### Study 4

In [ ]:
userItemMatrix = ratingsDF.pivot(index='userId', columns='movieId', values='rating').fillna(0)
userItemArray = userItemMatrix.to_numpy()
userItemArrayValidation = userItemArray.copy()

In [ ]:
np.random.seed(17)

numToRemove = int(len(userItemArray) * 0.1)
removeIndices = np.random.choice(len(userItemArray), numToRemove, replace=False)
for idx in removeIndices:
    for i in range(len(userItemArrayValidation[idx])):
        userItemArrayValidation[idx][i] = 0

In [ ]:
def matrix_factorization(R, P, Q, K, steps=500, alpha=0.0004, beta=0.02):
    Q = Q.T
    error=[]
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        error.append(e)
        if e < 0.001:
            break
    # for i in range(len(error)):
    #     print(error[i])    
    return P, Q.T

R = np.array(userItemArrayValidation)
N = len(R)
M = len(R[0])
K = 10
P = np.random.rand(N,K)
Q = np.random.rand(M,K)
nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)

171537.57721497118
141995.14121080638
127861.69600039083
119304.24946871932
113396.62396276848
109002.60601750921
105575.96808242866
102813.18060938026
100528.86144782501
98602.20426977104
96950.64835735118
95515.65079971818
94254.44597834
93135.01241220415
92132.86584222502
91228.9438407439
90408.16923267354
89658.44991408098
88969.96726351578
88334.66011963476
87745.84415224417
87197.92676576563
86686.19056874907
86206.62682100643
85755.80582685905
85330.77499681884
84928.97787937301
84548.18926267036
84186.46271868283
83842.08787335652
83513.55534770206
83199.52779926301
82898.81585287493
82610.35797847137
82333.20357697534
82066.49869042309
81809.47387133012
81561.4338388056
81321.74862102464
81089.84594010869
80865.2046406421
80647.34899841933
80435.84377496381
80230.28990629896
80030.32073307855
79835.59869452628
79645.81242115775
79460.67417122694
79279.91756468039
79103.29557509974
78930.57874615099
78761.55360388203
78596.02124023033
78433.79604687663
78274.70458080636
78118.58454638338
77965.28387989044
77814.65992492823
77666.57868831356
77520.91416735781
77377.5477409686
77236.3676172707
77097.26833202214
76960.15029232015
76824.91936090197
76691.48647702175
76559.76730998683
76429.68194230647
76301.15457945321
76174.11328365447
76048.4897294489
75924.2189789492
75801.23927492804
75679.49185016037
75558.92075148108
75439.47267729578
75321.09682723292
75203.74476308771
75087.3702798161
74971.92928589776
74857.3796922622
74743.68130891687
74630.79574886426
74518.68633845051
74407.31803386188
74296.65734310275
74186.67225307612
74077.33216142784
73968.60781262399
73860.47123812429
73752.89570016552
73645.85563895109
73539.32662308733
73433.28530276596
73327.70936576887
73222.57749592232
73117.86933382777
73013.56543980735
72909.64725872855
72806.09708678999
72702.89803990671
72600.03402377361
72497.4897053286
72395.25048565635
72293.30247410398
72191.6324636482
72090.22790732946
71989.07689570765
71888.16813534062
71787.4909280921
71687.03515131262
71586.79123879636
71486.7501624743
71386.90341478461
71287.24299170305
71187.76137630912
71088.45152302974
70989.30684231353
70890.32118580349
70791.488832061
70692.80447262587
70594.26319855425
70495.86048733114
70397.5921901236
70299.45451941015
70201.44403693697
70103.55764197269
70005.79255984731
69908.14633081808
69810.61679909941
69713.20210229633
69615.90066094263
69518.71116833533
69421.63258056174
69324.66410679049
69227.80519967618
69131.05554604382
69034.41505772834
68937.88386255996
68841.46229559061
68745.15089043227
68648.95037081899
68552.86164225562
68456.88578389952
68361.02404054177
68265.27781476831
68169.64865925394
68074.1382691976
67978.74847492282
67883.4812346061
67788.33862714595
67693.32284515366
67598.43618813776
67503.68105574918
67409.05994123075
67314.57542496666
67220.23016817016
67126.0269067346
67031.96844517227
66938.05765076607
66844.29744777379
66750.69081182315
66657.24076443496
66563.95036767665
66470.822718965
66377.86094601406
66285.06820188131
66192.44766022699
66100.00251064125
66007.73595417406
65915.65119895023
65823.75145598745
65732.03993510164
65640.5198409794
65549.19436940101
65458.066703584314
65367.14001069244
65276.417438456774
65185.90211196899
65095.597130588496
65005.505565004714
64915.63045442605
64825.97480390787
64736.54158183926
64647.333717514804
64558.35409888064
64469.60557040554
64381.090931057166
64292.81293242591
64204.774276962016
64116.97761635924
64029.42555001124
63942.120623637915
63855.06532798
63768.26209764278
63681.71331004162
63595.421284414966
63509.38828099535
63423.61650026012
63338.10808226503
63252.86510608548
63167.88958935953
63083.18348788082
62998.748695348244
62914.58704310057
62830.700300009776
62747.09017243416
62663.7583041867
62580.706276667916
62497.935608973545
62415.44775813086
62333.24411935603
62251.326026378476
62169.694751839306
62088.351507697575
62007.297445745346
61926.533658087355
61846.06117775744
61765.88097927296
61685.99397934407
61606.401037476375
61527.10295674473
61448.10048450749
61369.39431316667
61290.98508098089
61212.87337286505
61135.05972122769
61057.54460683487
60980.32845966845
60903.41165983405
60826.79453842926
60750.477378474294
60674.46041582598
60598.74384012024
60523.327795677986
60448.21238246485
60373.39765703249
60298.88363345728
60224.670284291686
60150.75754151127
60077.145297453426
60003.83340577536
59930.821682380505
59858.10990635069
59785.69782090194
59713.58513428462
59641.77152070472
59570.25662125297
59499.04004480084
59428.12136887629
59357.500140585034
59287.17587746552
59217.14806834352
59147.416174221165
59077.979629104426
59008.83784082629
58939.99019188861
58871.43604025431
58803.17472017817
58735.205542944976
58667.5277976816
58600.1407520911
58533.04365323091
58466.23572821495
58399.71618494947
58333.48421283925
58267.53898349043
58201.87965137262
58136.50535449986
58071.41521508912
58006.608340177365
57942.08382227449
57877.84073997016
57813.878158525076
57750.195130452215
57686.79069612869
57623.66388429965
57560.81371268004
57498.239188444255
57435.939308785244
57373.91306138146
57312.15942494428
57250.677369655175
57189.46585766919
57128.523843552604
57067.85027474602
57007.44409198574
56947.30422973499
56887.429616603826
56827.81917573705
56768.4718252021
56709.38647837172
56650.56204430893
56591.997428083785
56533.69153116546
56475.64325171858
56417.85148495622
56360.31512344531
56303.03305740366
56246.00417502083
56189.22736272219
56132.70150544487
56076.425486936256
56020.398189979845
55964.61849666202
55909.0852886219
55853.79744726337
55798.7538540099
55743.95339049417
55689.39493879106
55635.07738160877
55580.99960249112
55527.16048600207
55473.55891790043
55420.19378533494
55367.06397697953
55314.1683832282
55261.505896339455
55209.07541055514
55156.87582229911
55104.906030259604
55053.164935543835
55001.65144182496
54950.36445540421
54899.302885392586
54848.465643767384
54797.85164550483
54747.45980866637
54697.28905450461
54647.33830754278
54597.60649566607
54548.09255019844
54498.7954059891
54449.71400147106
54400.84727874974
54352.19418364208
54303.75366577177
54255.524678593625
54207.506179464486
54159.6971296986
54112.09649460753
54064.70324355036
54017.516349973244
53970.534791438855
53923.75754968229
53877.18361063284
53830.811964442844
53784.64160551278
53738.67153253528
53692.900748499254
53647.32826072143
53601.95308085562
53556.77422492884
53511.790713332884
53467.00157085683
53422.405826683025
53378.00251440339
53333.79067203654
53289.76934201306
53245.937571198025
53202.29441088285
53158.83891680173
53115.570149104664
53072.487172396635
53029.589055686716
52986.87487243096
52944.343700492056
52901.99462216568
52859.82672413854
52817.839097511714
52776.03083777475
52734.40104480143
52692.948822838705
52651.673280503725
52610.57353075009
52569.6486908834
52528.89788252212
52488.32023161462
52447.914868392974
52407.68092737527
52367.6175473511
52327.72387135426
52287.99904666379
52248.44222478017
52209.05256138656
52169.82921637677
52130.77135379966
52091.878141858564
52053.14875287878
52014.582363314206
51976.17815370303
51937.935308670116
51899.853016887326
51861.930471074535
51824.166867956796
51786.561408287154
51749.11329677082
51711.8217420958
51674.68595687813
51637.70515766776
51600.87856491444
51564.20540294725
51527.68489997406
51491.31628803301
51455.098802994566
51419.03168454529
51383.114176146475
51347.34552502568
51311.72498217463
51276.2518023063
51240.9252438463
51205.74456891463
51170.70904329826
51135.81793644813
51101.07052144863
51066.46607500098
51032.00387741137
50997.6832125622
50963.50336789879
50929.46363442428
50895.56330665681
50861.801682633115
50828.178063882515
50794.691755411346
50761.34206568047
50728.128306598956
50695.04979350124
50662.1058451315
50629.29578362036
50596.618934478785
50564.07462658131
50531.66219214261
50499.380966713434
50467.230289142535
50435.209501587604
50403.317949497956
50371.554981564
50339.919949745934
50308.412209247464
50277.031118478175
50245.776039063836
50214.64633582241
50183.64137675934
50152.76053303525
50122.00317895959
50091.36869199471
50060.85645271114
50030.46584480262
50000.19625504849
49970.04707332109
49940.017692556976
49910.10750875637
49880.31592096033
49850.64233123963
49821.08614469518
49791.64676941738
49762.32361650877
49733.116100046136
49704.02363707284
49675.04564759788
49646.181554569586
49617.43078387312
49588.792764316044
49560.266927616096
49531.85270838797
49503.549544137844
49475.35687524433
49447.27414495009
49419.300799354445
49391.43628739637
49363.680060845356
49336.03157429118
49308.49028513127
49281.05565356688
49253.72714257483
49226.50421791993
49199.386348119806
49172.373004462104
49145.46366095876
49118.657794376144
49091.954884191524
49065.35441259088
49038.85586446808
49012.458727412435
48986.16249168153
48959.96665021672
48933.87069861146
48907.87413511027
48881.976460594145
48856.177178581005
48830.47579520443
48804.8718192062
48779.364761925695
48753.95413729007
48728.6394618094
48703.420254561825
48678.2960371746
48653.26633383606
48628.33067126437
48603.48857871006

In [105]:
np.random.seed(18)
user1 = np.random.randint(0, len(userItemArray))
while True:
    movie1 = np.random.randint(0, len(userItemArray[user1]))
    if userItemArray[user1][movie1] == 0:
        break
print(f"user {user1} is predicted to have rated movie {movie1}: {nR[user1][movie1]:.1f}")
top10_user1 = np.argsort(nR[user1])[::-1][:10]

print(f"Top 10 predicted ratings for user {user1}:")

for i in top10_user1:
    print(f"movie {i}: {nR[user1][i]:.1f}")

user 298 is predicted to have rated movie 2885: 3.4
Top 10 predicted ratings for user 298:
movie 8831: 6.4
movie 2724: 6.3
movie 8766: 6.1
movie 4979: 6.1
movie 3727: 6.1
movie 7968: 6.0
movie 4448: 6.0
movie 6591: 6.0
movie 8639: 6.0
movie 6490: 6.0

In [106]:
np.random.seed(19)
user2 = np.random.randint(0, len(userItemArray))
while True:
    movie2 = np.random.randint(0, len(userItemArray[user2]))
    if userItemArray[user2][movie2] == 0:
        break
print(f"user {user2} is predicted to have rated movie {movie2}: {nR[user2][movie2]:.1f}")
top10_user2 = np.argsort(nR[user2])[::-1][:10]

print(f"Top 10 predicted ratings for user {user2}:")

for i in top10_user2:
    print(f"movie {i}: {nR[user2][i]:.1f}")

user 605 is predicted to have rated movie 757: 4.1
Top 10 predicted ratings for user 605:
movie 8831: 6.0
movie 5510: 5.9
movie 5759: 5.9
movie 5353: 5.8
movie 4296: 5.8
movie 7692: 5.7
movie 4979: 5.7
movie 7968: 5.7
movie 8766: 5.7
movie 7420: 5.6

In [107]:
np.random.seed(20)
user3 = np.random.randint(0, len(userItemArray))
while True:
    movie3 = np.random.randint(0, len(userItemArray[user3]))
    if userItemArray[user3][movie3] == 0:
        break
print(f"user {user3} is predicted to have rated movie {movie3}: {nR[user3][movie3]:.1f}")
top10_user3 = np.argsort(nR[user3])[::-1][:10]

print(f"Top 10 predicted ratings for user {user3}:")

for i in top10_user3:
    print(f"movie {i}: {nR[user3][i]:.1f}")

user 355 is predicted to have rated movie 4367: 3.8
Top 10 predicted ratings for user 355:
movie 6591: 5.8
movie 7568: 5.6
movie 274: 5.4
movie 7946: 5.4
movie 6064: 5.4
movie 1244: 5.3
movie 8744: 5.3
movie 5353: 5.3
movie 2991: 5.3
movie 4979: 5.3

evaluate 1

In [ ]:
answer = 0
for idx in removeIndices:
    partialAnswer = 0
    yTrue = userItemArray[idx]
    yTruePart = []
    yPred = nR[idx]
    yPredPart = []
    for i in range(len(userItemArray[idx])):
        if userItemArray[idx][i] > 0:
            yTruePart.append(userItemArray[idx][i])
            yPredPart.append(nR[idx][i])
    partialAnswer = np.mean((np.array(yTruePart) - np.array(yPredPart))**2)
    answer += partialAnswer
answer /= len(removeIndices)
print(f"Mean Squared Error: {answer}")

Mean Squared Error: 0.39222938943663144

evaluate 2

In [ ]:
userItemBoolean = (userItemArray >= 4.0).astype(bool)

In [ ]:
precisionAt5 = []
for i in range(len(userItemBoolean)):
    top5Indices = np.argsort(nR[i])[::-1][:5]
    summation = 0
    for j in top5Indices:
        if userItemBoolean[i][j]:
            summation += 1
    precision = summation / 5.0
    precisionAt5.append(precision)
    print(f"User {i+1}: Precision@5 = {precision}")

User 1: Precision@5 = 0.0
User 2: Precision@5 = 0.0
User 3: Precision@5 = 0.0
User 4: Precision@5 = 0.0
User 5: Precision@5 = 0.0
User 6: Precision@5 = 0.0
User 7: Precision@5 = 0.0
User 8: Precision@5 = 0.0
User 9: Precision@5 = 0.0
User 10: Precision@5 = 0.0
User 11: Precision@5 = 0.0
User 12: Precision@5 = 0.0
User 13: Precision@5 = 0.0
User 14: Precision@5 = 0.0
User 15: Precision@5 = 0.6
User 16: Precision@5 = 0.0
User 17: Precision@5 = 0.2
User 18: Precision@5 = 0.0
User 19: Precision@5 = 0.0
User 20: Precision@5 = 0.0
User 21: Precision@5 = 0.0
User 22: Precision@5 = 0.0
User 23: Precision@5 = 0.0
User 24: Precision@5 = 0.0
User 25: Precision@5 = 0.0
User 26: Precision@5 = 0.0
User 27: Precision@5 = 0.0
User 28: Precision@5 = 0.0
User 29: Precision@5 = 0.0
User 30: Precision@5 = 0.0
User 31: Precision@5 = 0.0
User 32: Precision@5 = 0.0
User 33: Precision@5 = 0.0
User 34: Precision@5 = 0.0
User 35: Precision@5 = 0.0
User 36: Precision@5 = 0.0
User 37: Precision@5 = 0.0
User 38: Precision@5 = 0.0
User 39: Precision@5 = 0.0
User 40: Precision@5 = 0.0
User 41: Precision@5 = 0.0
User 42: Precision@5 = 0.0
User 43: Precision@5 = 0.0
User 44: Precision@5 = 0.0
User 45: Precision@5 = 0.0
User 46: Precision@5 = 0.0
User 47: Precision@5 = 0.0
User 48: Precision@5 = 0.0
User 49: Precision@5 = 0.0
User 50: Precision@5 = 0.0
User 51: Precision@5 = 0.0
User 52: Precision@5 = 0.0
User 53: Precision@5 = 0.0
User 54: Precision@5 = 0.0
User 55: Precision@5 = 0.0
User 56: Precision@5 = 0.0
User 57: Precision@5 = 0.0
User 58: Precision@5 = 0.0
User 59: Precision@5 = 0.0
User 60: Precision@5 = 0.0
User 61: Precision@5 = 0.0
User 62: Precision@5 = 0.0
User 63: Precision@5 = 0.0
User 64: Precision@5 = 0.0
User 65: Precision@5 = 0.0
User 66: Precision@5 = 0.0
User 67: Precision@5 = 0.0
User 68: Precision@5 = 0.0
User 69: Precision@5 = 0.0
User 70: Precision@5 = 0.0
User 71: Precision@5 = 0.0
User 72: Precision@5 = 0.0
User 73: Precision@5 = 0.0
User 74: Precision@5 = 0.0
User 75: Precision@5 = 0.0
User 76: Precision@5 = 0.0
User 77: Precision@5 = 0.0
User 78: Precision@5 = 0.0
User 79: Precision@5 = 0.0
User 80: Precision@5 = 0.0
User 81: Precision@5 = 0.0
User 82: Precision@5 = 0.0
User 83: Precision@5 = 0.0
User 84: Precision@5 = 0.0
User 85: Precision@5 = 0.0
User 86: Precision@5 = 0.0
User 87: Precision@5 = 0.0
User 88: Precision@5 = 0.0
User 89: Precision@5 = 0.0
User 90: Precision@5 = 0.0
User 91: Precision@5 = 0.0
User 92: Precision@5 = 0.0
User 93: Precision@5 = 0.0
User 94: Precision@5 = 0.0
User 95: Precision@5 = 0.0
User 96: Precision@5 = 0.0
User 97: Precision@5 = 0.0
User 98: Precision@5 = 0.0
User 99: Precision@5 = 0.0
User 100: Precision@5 = 0.0
User 101: Precision@5 = 0.0
User 102: Precision@5 = 0.0
User 103: Precision@5 = 0.0
User 104: Precision@5 = 0.0
User 105: Precision@5 = 0.0
User 106: Precision@5 = 0.0
User 107: Precision@5 = 0.0
User 108: Precision@5 = 0.0
User 109: Precision@5 = 0.0
User 110: Precision@5 = 0.0
User 111: Precision@5 = 0.0
User 112: Precision@5 = 0.0
User 113: Precision@5 = 0.0
User 114: Precision@5 = 0.0
User 115: Precision@5 = 0.0
User 116: Precision@5 = 0.0
User 117: Precision@5 = 0.0
User 118: Precision@5 = 0.0
User 119: Precision@5 = 0.0
User 120: Precision@5 = 0.0
User 121: Precision@5 = 0.0
User 122: Precision@5 = 0.0
User 123: Precision@5 = 0.0
User 124: Precision@5 = 0.0
User 125: Precision@5 = 0.0
User 126: Precision@5 = 0.0
User 127: Precision@5 = 0.0
User 128: Precision@5 = 0.0
User 129: Precision@5 = 0.0
User 130: Precision@5 = 0.0
User 131: Precision@5 = 0.0
User 132: Precision@5 = 0.0
User 133: Precision@5 = 0.0
User 134: Precision@5 = 0.0
User 135: Precision@5 = 0.0
User 136: Precision@5 = 0.0
User 137: Precision@5 = 0.0
User 138: Precision@5 = 0.0
User 139: Precision@5 = 0.0
User 140: Precision@5 = 0.0
User 141: Precision@5 = 0.0
User 142: Precision@5 = 0.0
User 143: Precision@5 = 0.0
User 144: Precision@5 = 0.0
User 145: Precision@5 = 0.0
User 146: Precision@5 = 0.0
User 147: Precision@5 = 0.0
User 148: Precision@5 = 0.0
User 149: Precision@5 = 0.0
User 150: Precision@5 = 0.0
User 151: Precision@5 = 0.0
User 152: Precision@5 = 0.0
User 153: Precision@5 = 0.0
User 154: Precision@5 = 0.0
User 155: Precision@5 = 0.0
User 156: Precision@5 = 0.0
User 157: Precision@5 = 0.0
User 158: Precision@5 = 0.0
User 159: Precision@5 = 0.0
User 160: Precision@5 = 0.0
User 161: Precision@5 = 0.0
User 162: Precision@5 = 0.0
User 163: Precision@5 = 0.0
User 164: Precision@5 = 0.0
User 165: Precision@5 = 0.2
User 166: Precision@5 = 0.0
User 167: Precision@5 = 0.0
User 168: Precision@5 = 0.0
User 169: Precision@5 = 0.0
User 170: Precision@5 = 0.0
User 171: Precision@5 = 0.0
User 172: Precision@5 = 0.0
User 173: Precision@5 = 0.0
User 174: Precision@5 = 0.0
User 175: Precision@5 = 0.0
User 176: Precision@5 = 0.0
User 177: Precision@5 = 0.0
User 178: Precision@5 = 0.0
User 179: Precision@5 = 0.0
User 180: Precision@5 = 0.0
User 181: Precision@5 = 0.0
User 182: Precision@5 = 0.0
User 183: Precision@5 = 0.0
User 184: Precision@5 = 0.0
User 185: Precision@5 = 0.0
User 186: Precision@5 = 0.0
User 187: Precision@5 = 0.0
User 188: Precision@5 = 0.0
User 189: Precision@5 = 0.0
User 190: Precision@5 = 0.0
User 191: Precision@5 = 0.0
User 192: Precision@5 = 0.0
User 193: Precision@5 = 0.0
User 194: Precision@5 = 0.0
User 195: Precision@5 = 0.0
User 196: Precision@5 = 0.0
User 197: Precision@5 = 0.0
User 198: Precision@5 = 0.0
User 199: Precision@5 = 0.0
User 200: Precision@5 = 0.0
User 201: Precision@5 = 0.0
User 202: Precision@5 = 0.0
User 203: Precision@5 = 0.0
User 204: Precision@5 = 0.0
User 205: Precision@5 = 0.0
User 206: Precision@5 = 0.0
User 207: Precision@5 = 0.0
User 208: Precision@5 = 0.0
User 209: Precision@5 = 0.0
User 210: Precision@5 = 0.0
User 211: Precision@5 = 0.0
User 212: Precision@5 = 0.0
User 213: Precision@5 = 0.2
User 214: Precision@5 = 0.0
User 215: Precision@5 = 0.0
User 216: Precision@5 = 0.0
User 217: Precision@5 = 0.0
User 218: Precision@5 = 0.0
User 219: Precision@5 = 0.0
User 220: Precision@5 = 0.2
User 221: Precision@5 = 0.0
User 222: Precision@5 = 0.0
User 223: Precision@5 = 0.0
User 224: Precision@5 = 0.0
User 225: Precision@5 = 0.0
User 226: Precision@5 = 0.0
User 227: Precision@5 = 0.0
User 228: Precision@5 = 0.0
User 229: Precision@5 = 0.0
User 230: Precision@5 = 0.0
User 231: Precision@5 = 0.0
User 232: Precision@5 = 0.0
User 233: Precision@5 = 0.0
User 234: Precision@5 = 0.0
User 235: Precision@5 = 0.0
User 236: Precision@5 = 0.0
User 237: Precision@5 = 0.0
User 238: Precision@5 = 0.0
User 239: Precision@5 = 0.0
User 240: Precision@5 = 0.0
User 241: Precision@5 = 0.0
User 242: Precision@5 = 0.0
User 243: Precision@5 = 0.0
User 244: Precision@5 = 0.0
User 245: Precision@5 = 0.0
User 246: Precision@5 = 0.0
User 247: Precision@5 = 0.0
User 248: Precision@5 = 0.0
User 249: Precision@5 = 0.0
User 250: Precision@5 = 0.0
User 251: Precision@5 = 0.0
User 252: Precision@5 = 0.0
User 253: Precision@5 = 0.0
User 254: Precision@5 = 0.0
User 255: Precision@5 = 0.0
User 256: Precision@5 = 0.0
User 257: Precision@5 = 0.0
User 258: Precision@5 = 0.0
User 259: Precision@5 = 0.0
User 260: Precision@5 = 0.0
User 261: Precision@5 = 0.0
User 262: Precision@5 = 0.0
User 263: Precision@5 = 0.0
User 264: Precision@5 = 0.0
User 265: Precision@5 = 0.0
User 266: Precision@5 = 0.0
User 267: Precision@5 = 0.0
User 268: Precision@5 = 0.0
User 269: Precision@5 = 0.0
User 270: Precision@5 = 0.0
User 271: Precision@5 = 0.0
User 272: Precision@5 = 0.0
User 273: Precision@5 = 0.0
User 274: Precision@5 = 0.0
User 275: Precision@5 = 0.0
User 276: Precision@5 = 0.0
User 277: Precision@5 = 0.0
User 278: Precision@5 = 0.0
User 279: Precision@5 = 0.0
User 280: Precision@5 = 0.0
User 281: Precision@5 = 0.0
User 282: Precision@5 = 0.0
User 283: Precision@5 = 0.0
User 284: Precision@5 = 0.0
User 285: Precision@5 = 0.0
User 286: Precision@5 = 0.0
User 287: Precision@5 = 0.0
User 288: Precision@5 = 0.0
User 289: Precision@5 = 0.0
User 290: Precision@5 = 0.0
User 291: Precision@5 = 0.0
User 292: Precision@5 = 0.0
User 293: Precision@5 = 0.0
User 294: Precision@5 = 0.0
User 295: Precision@5 = 0.0
User 296: Precision@5 = 0.0
User 297: Precision@5 = 0.0
User 298: Precision@5 = 0.0
User 299: Precision@5 = 0.0
User 300: Precision@5 = 0.0
User 301: Precision@5 = 0.0
User 302: Precision@5 = 0.0
User 303: Precision@5 = 0.0
User 304: Precision@5 = 0.0
User 305: Precision@5 = 0.0
User 306: Precision@5 = 0.0
User 307: Precision@5 = 0.0
User 308: Precision@5 = 0.0
User 309: Precision@5 = 0.0
User 310: Precision@5 = 0.0
User 311: Precision@5 = 0.0
User 312: Precision@5 = 0.0
User 313: Precision@5 = 0.0
User 314: Precision@5 = 0.0
User 315: Precision@5 = 0.0
User 316: Precision@5 = 0.0
User 317: Precision@5 = 0.0
User 318: Precision@5 = 0.0
User 319: Precision@5 = 0.0
User 320: Precision@5 = 0.0
User 321: Precision@5 = 0.0
User 322: Precision@5 = 0.0
User 323: Precision@5 = 0.0
User 324: Precision@5 = 0.0
User 325: Precision@5 = 0.0
User 326: Precision@5 = 0.0
User 327: Precision@5 = 0.0
User 328: Precision@5 = 0.0
User 329: Precision@5 = 0.0
User 330: Precision@5 = 0.0
User 331: Precision@5 = 0.0
User 332: Precision@5 = 0.0
User 333: Precision@5 = 0.0
User 334: Precision@5 = 0.0
User 335: Precision@5 = 0.0
User 336: Precision@5 = 0.0
User 337: Precision@5 = 0.0
User 338: Precision@5 = 0.0
User 339: Precision@5 = 0.0
User 340: Precision@5 = 0.0
User 341: Precision@5 = 0.0
User 342: Precision@5 = 0.0
User 343: Precision@5 = 0.0
User 344: Precision@5 = 0.0
User 345: Precision@5 = 0.0
User 346: Precision@5 = 0.0
User 347: Precision@5 = 0.0
User 348: Precision@5 = 0.0
User 349: Precision@5 = 0.0
User 350: Precision@5 = 0.0
User 351: Precision@5 = 0.0
User 352: Precision@5 = 0.0
User 353: Precision@5 = 0.0
User 354: Precision@5 = 0.0
User 355: Precision@5 = 0.0
User 356: Precision@5 = 0.0
User 357: Precision@5 = 0.0
User 358: Precision@5 = 0.0
User 359: Precision@5 = 0.0
User 360: Precision@5 = 0.0
User 361: Precision@5 = 0.0
User 362: Precision@5 = 0.0
User 363: Precision@5 = 0.0
User 364: Precision@5 = 0.0
User 365: Precision@5 = 0.0
User 366: Precision@5 = 0.0
User 367: Precision@5 = 0.2
User 368: Precision@5 = 0.0
User 369: Precision@5 = 0.0
User 370: Precision@5 = 0.0
User 371: Precision@5 = 0.0
User 372: Precision@5 = 0.0
User 373: Precision@5 = 0.0
User 374: Precision@5 = 0.0
User 375: Precision@5 = 0.0
User 376: Precision@5 = 0.0
User 377: Precision@5 = 0.0
User 378: Precision@5 = 0.0
User 379: Precision@5 = 0.0
User 380: Precision@5 = 0.0
User 381: Precision@5 = 0.0
User 382: Precision@5 = 0.0
User 383: Precision@5 = 0.0
User 384: Precision@5 = 0.0
User 385: Precision@5 = 0.0
User 386: Precision@5 = 0.0
User 387: Precision@5 = 0.0
User 388: Precision@5 = 0.0
User 389: Precision@5 = 0.0
User 390: Precision@5 = 0.0
User 391: Precision@5 = 0.0
User 392: Precision@5 = 0.0
User 393: Precision@5 = 0.0
User 394: Precision@5 = 0.0
User 395: Precision@5 = 0.0
User 396: Precision@5 = 0.0
User 397: Precision@5 = 0.0
User 398: Precision@5 = 0.0
User 399: Precision@5 = 0.0
User 400: Precision@5 = 0.0
User 401: Precision@5 = 0.0
User 402: Precision@5 = 0.0
User 403: Precision@5 = 0.0
User 404: Precision@5 = 0.0
User 405: Precision@5 = 0.0
User 406: Precision@5 = 0.0
User 407: Precision@5 = 0.0
User 408: Precision@5 = 0.0
User 409: Precision@5 = 0.0
User 410: Precision@5 = 0.0
User 411: Precision@5 = 0.0
User 412: Precision@5 = 0.0
User 413: Precision@5 = 0.0
User 414: Precision@5 = 0.0
User 415: Precision@5 = 0.0
User 416: Precision@5 = 0.0
User 417: Precision@5 = 0.0
User 418: Precision@5 = 0.0
User 419: Precision@5 = 0.0
User 420: Precision@5 = 0.0
User 421: Precision@5 = 0.0
User 422: Precision@5 = 0.0
User 423: Precision@5 = 0.0
User 424: Precision@5 = 0.0
User 425: Precision@5 = 0.2
User 426: Precision@5 = 0.6
User 427: Precision@5 = 0.0
User 428: Precision@5 = 0.0
User 429: Precision@5 = 0.0
User 430: Precision@5 = 0.0
User 431: Precision@5 = 0.0
User 432: Precision@5 = 0.0
User 433: Precision@5 = 0.0
User 434: Precision@5 = 0.0
User 435: Precision@5 = 0.0
User 436: Precision@5 = 0.0
User 437: Precision@5 = 0.0
User 438: Precision@5 = 0.0
User 439: Precision@5 = 0.0
User 440: Precision@5 = 0.0
User 441: Precision@5 = 0.0
User 442: Precision@5 = 0.0
User 443: Precision@5 = 0.0
User 444: Precision@5 = 0.0
User 445: Precision@5 = 0.0
User 446: Precision@5 = 0.0
User 447: Precision@5 = 0.0
User 448: Precision@5 = 0.0
User 449: Precision@5 = 0.0
User 450: Precision@5 = 0.0
User 451: Precision@5 = 0.0
User 452: Precision@5 = 0.0
User 453: Precision@5 = 0.0
User 454: Precision@5 = 0.0
User 455: Precision@5 = 0.0
User 456: Precision@5 = 0.0
User 457: Precision@5 = 0.2
User 458: Precision@5 = 0.0
User 459: Precision@5 = 0.0
User 460: Precision@5 = 0.0
User 461: Precision@5 = 0.0
User 462: Precision@5 = 0.0
User 463: Precision@5 = 0.0
User 464: Precision@5 = 0.0
User 465: Precision@5 = 0.0
User 466: Precision@5 = 0.0
User 467: Precision@5 = 0.0
User 468: Precision@5 = 0.2
User 469: Precision@5 = 0.0
User 470: Precision@5 = 0.0
User 471: Precision@5 = 0.0
User 472: Precision@5 = 0.2
User 473: Precision@5 = 0.0
User 474: Precision@5 = 0.0
User 475: Precision@5 = 0.6
User 476: Precision@5 = 0.0
User 477: Precision@5 = 0.0
User 478: Precision@5 = 0.0
User 479: Precision@5 = 0.0
User 480: Precision@5 = 0.0
User 481: Precision@5 = 0.0
User 482: Precision@5 = 0.0
User 483: Precision@5 = 0.0
User 484: Precision@5 = 0.0
User 485: Precision@5 = 0.0
User 486: Precision@5 = 0.0
User 487: Precision@5 = 0.0
User 488: Precision@5 = 0.0
User 489: Precision@5 = 0.0
User 490: Precision@5 = 0.0
User 491: Precision@5 = 0.0
User 492: Precision@5 = 0.0
User 493: Precision@5 = 0.0
User 494: Precision@5 = 0.0
User 495: Precision@5 = 0.0
User 496: Precision@5 = 0.0
User 497: Precision@5 = 0.0
User 498: Precision@5 = 0.0
User 499: Precision@5 = 0.0
User 500: Precision@5 = 0.0
User 501: Precision@5 = 0.0
User 502: Precision@5 = 0.0
User 503: Precision@5 = 0.0
User 504: Precision@5 = 0.0
User 505: Precision@5 = 0.0
User 506: Precision@5 = 0.0
User 507: Precision@5 = 0.0
User 508: Precision@5 = 0.0
User 509: Precision@5 = 0.0
User 510: Precision@5 = 0.0
User 511: Precision@5 = 0.0
User 512: Precision@5 = 0.0
User 513: Precision@5 = 0.0
User 514: Precision@5 = 0.0
User 515: Precision@5 = 0.0
User 516: Precision@5 = 0.0
User 517: Precision@5 = 0.0
User 518: Precision@5 = 0.0
User 519: Precision@5 = 0.0
User 520: Precision@5 = 0.0
User 521: Precision@5 = 0.0
User 522: Precision@5 = 0.0
User 523: Precision@5 = 0.0
User 524: Precision@5 = 0.0
User 525: Precision@5 = 0.0
User 526: Precision@5 = 0.0
User 527: Precision@5 = 0.0
User 528: Precision@5 = 0.0
User 529: Precision@5 = 0.0
User 530: Precision@5 = 0.0
User 531: Precision@5 = 0.0
User 532: Precision@5 = 0.0
User 533: Precision@5 = 0.0
User 534: Precision@5 = 0.0
User 535: Precision@5 = 0.0
User 536: Precision@5 = 0.0
User 537: Precision@5 = 0.0
User 538: Precision@5 = 0.0
User 539: Precision@5 = 0.0
User 540: Precision@5 = 0.0
User 541: Precision@5 = 0.0
User 542: Precision@5 = 0.0
User 543: Precision@5 = 0.0
User 544: Precision@5 = 0.0
User 545: Precision@5 = 0.0
User 546: Precision@5 = 0.0
User 547: Precision@5 = 0.2
User 548: Precision@5 = 0.0
User 549: Precision@5 = 0.0
User 550: Precision@5 = 0.0
User 551: Precision@5 = 0.0
User 552: Precision@5 = 0.0
User 553: Precision@5 = 0.2
User 554: Precision@5 = 0.0
User 555: Precision@5 = 0.0
User 556: Precision@5 = 0.0
User 557: Precision@5 = 0.0
User 558: Precision@5 = 0.0
User 559: Precision@5 = 0.0
User 560: Precision@5 = 0.0
User 561: Precision@5 = 0.0
User 562: Precision@5 = 0.0
User 563: Precision@5 = 0.0
User 564: Precision@5 = 0.0
User 565: Precision@5 = 0.0
User 566: Precision@5 = 0.0
User 567: Precision@5 = 0.0
User 568: Precision@5 = 0.0
User 569: Precision@5 = 0.0
User 570: Precision@5 = 0.0
User 571: Precision@5 = 0.0
User 572: Precision@5 = 0.0
User 573: Precision@5 = 0.0
User 574: Precision@5 = 0.0
User 575: Precision@5 = 0.0
User 576: Precision@5 = 0.0
User 577: Precision@5 = 0.0
User 578: Precision@5 = 0.2
User 579: Precision@5 = 0.2
User 580: Precision@5 = 0.0
User 581: Precision@5 = 0.0
User 582: Precision@5 = 0.0
User 583: Precision@5 = 0.0
User 584: Precision@5 = 0.0
User 585: Precision@5 = 0.0
User 586: Precision@5 = 0.0
User 587: Precision@5 = 0.0
User 588: Precision@5 = 0.0
User 589: Precision@5 = 0.0
User 590: Precision@5 = 0.0
User 591: Precision@5 = 0.0
User 592: Precision@5 = 0.0
User 593: Precision@5 = 0.0
User 594: Precision@5 = 0.0
User 595: Precision@5 = 0.0
User 596: Precision@5 = 0.0
User 597: Precision@5 = 0.0
User 598: Precision@5 = 0.0
User 599: Precision@5 = 0.0
User 600: Precision@5 = 0.0
User 601: Precision@5 = 0.0
User 602: Precision@5 = 0.0
User 603: Precision@5 = 0.0
User 604: Precision@5 = 0.0
User 605: Precision@5 = 0.0
User 606: Precision@5 = 0.0
User 607: Precision@5 = 0.0
User 608: Precision@5 = 0.0
User 609: Precision@5 = 0.0
User 610: Precision@5 = 0.0
User 611: Precision@5 = 0.0
User 612: Precision@5 = 0.0
User 613: Precision@5 = 0.0
User 614: Precision@5 = 0.0
User 615: Precision@5 = 0.0
User 616: Precision@5 = 0.0
User 617: Precision@5 = 0.0
User 618: Precision@5 = 0.0
User 619: Precision@5 = 0.0
User 620: Precision@5 = 0.0
User 621: Precision@5 = 0.0
User 622: Precision@5 = 0.0
User 623: Precision@5 = 0.0
User 624: Precision@5 = 0.0
User 625: Precision@5 = 0.0
User 626: Precision@5 = 0.0
User 627: Precision@5 = 0.0
User 628: Precision@5 = 0.0
User 629: Precision@5 = 0.2
User 630: Precision@5 = 0.0
User 631: Precision@5 = 0.0
User 632: Precision@5 = 0.0
User 633: Precision@5 = 0.0
User 634: Precision@5 = 0.0
User 635: Precision@5 = 0.0
User 636: Precision@5 = 0.0
User 637: Precision@5 = 0.0
User 638: Precision@5 = 0.0
User 639: Precision@5 = 0.0
User 640: Precision@5 = 0.0
User 641: Precision@5 = 0.0
User 642: Precision@5 = 0.0
User 643: Precision@5 = 0.0
User 644: Precision@5 = 0.0
User 645: Precision@5 = 0.0
User 646: Precision@5 = 0.0
User 647: Precision@5 = 0.0
User 648: Precision@5 = 0.0
User 649: Precision@5 = 0.0
User 650: Precision@5 = 0.0
User 651: Precision@5 = 0.0
User 652: Precision@5 = 0.0
User 653: Precision@5 = 0.0
User 654: Precision@5 = 0.0
User 655: Precision@5 = 0.0
User 656: Precision@5 = 0.0
User 657: Precision@5 = 0.0
User 658: Precision@5 = 0.0
User 659: Precision@5 = 0.0
User 660: Precision@5 = 0.0
User 661: Precision@5 = 0.0
User 662: Precision@5 = 0.0
User 663: Precision@5 = 0.0
User 664: Precision@5 = 0.0
User 665: Precision@5 = 0.0
User 666: Precision@5 = 0.0
User 667: Precision@5 = 0.0
User 668: Precision@5 = 0.0
User 669: Precision@5 = 0.0
User 670: Precision@5 = 0.0
User 671: Precision@5 = 0.0

In [ ]:
precisionAt10 = []
for i in range(len(userItemBoolean)):
    top10Indices = np.argsort(nR[i])[::-1][:10]
    summation = 0
    for j in top10Indices:
        if userItemBoolean[i][j]:
            summation += 1
    precision = summation / 10.0
    precisionAt10.append(precision)
    print(f"User {i+1}: Precision@10 = {precision}")

User 1: Precision@10 = 0.0
User 2: Precision@10 = 0.0
User 3: Precision@10 = 0.0
User 4: Precision@10 = 0.0
User 5: Precision@10 = 0.0
User 6: Precision@10 = 0.0
User 7: Precision@10 = 0.0
User 8: Precision@10 = 0.0
User 9: Precision@10 = 0.0
User 10: Precision@10 = 0.0
User 11: Precision@10 = 0.0
User 12: Precision@10 = 0.0
User 13: Precision@10 = 0.0
User 14: Precision@10 = 0.0
User 15: Precision@10 = 0.6
User 16: Precision@10 = 0.0
User 17: Precision@10 = 0.1
User 18: Precision@10 = 0.0
User 19: Precision@10 = 0.0
User 20: Precision@10 = 0.0
User 21: Precision@10 = 0.0
User 22: Precision@10 = 0.0
User 23: Precision@10 = 0.0
User 24: Precision@10 = 0.0
User 25: Precision@10 = 0.0
User 26: Precision@10 = 0.0
User 27: Precision@10 = 0.0
User 28: Precision@10 = 0.0
User 29: Precision@10 = 0.0
User 30: Precision@10 = 0.0
User 31: Precision@10 = 0.0
User 32: Precision@10 = 0.0
User 33: Precision@10 = 0.0
User 34: Precision@10 = 0.0
User 35: Precision@10 = 0.0
User 36: Precision@10 = 0.0
User 37: Precision@10 = 0.0
User 38: Precision@10 = 0.0
User 39: Precision@10 = 0.0
User 40: Precision@10 = 0.0
User 41: Precision@10 = 0.0
User 42: Precision@10 = 0.0
User 43: Precision@10 = 0.0
User 44: Precision@10 = 0.0
User 45: Precision@10 = 0.0
User 46: Precision@10 = 0.0
User 47: Precision@10 = 0.0
User 48: Precision@10 = 0.0
User 49: Precision@10 = 0.0
User 50: Precision@10 = 0.0
User 51: Precision@10 = 0.0
User 52: Precision@10 = 0.0
User 53: Precision@10 = 0.0
User 54: Precision@10 = 0.0
User 55: Precision@10 = 0.0
User 56: Precision@10 = 0.0
User 57: Precision@10 = 0.0
User 58: Precision@10 = 0.0
User 59: Precision@10 = 0.0
User 60: Precision@10 = 0.0
User 61: Precision@10 = 0.0
User 62: Precision@10 = 0.0
User 63: Precision@10 = 0.0
User 64: Precision@10 = 0.0
User 65: Precision@10 = 0.0
User 66: Precision@10 = 0.0
User 67: Precision@10 = 0.0
User 68: Precision@10 = 0.0
User 69: Precision@10 = 0.0
User 70: Precision@10 = 0.0
User 71: Precision@10 = 0.0
User 72: Precision@10 = 0.0
User 73: Precision@10 = 0.0
User 74: Precision@10 = 0.0
User 75: Precision@10 = 0.0
User 76: Precision@10 = 0.0
User 77: Precision@10 = 0.0
User 78: Precision@10 = 0.0
User 79: Precision@10 = 0.0
User 80: Precision@10 = 0.0
User 81: Precision@10 = 0.0
User 82: Precision@10 = 0.0
User 83: Precision@10 = 0.0
User 84: Precision@10 = 0.0
User 85: Precision@10 = 0.0
User 86: Precision@10 = 0.0
User 87: Precision@10 = 0.0
User 88: Precision@10 = 0.0
User 89: Precision@10 = 0.0
User 90: Precision@10 = 0.0
User 91: Precision@10 = 0.0
User 92: Precision@10 = 0.0
User 93: Precision@10 = 0.0
User 94: Precision@10 = 0.0
User 95: Precision@10 = 0.0
User 96: Precision@10 = 0.0
User 97: Precision@10 = 0.2
User 98: Precision@10 = 0.0
User 99: Precision@10 = 0.0
User 100: Precision@10 = 0.0
User 101: Precision@10 = 0.0
User 102: Precision@10 = 0.0
User 103: Precision@10 = 0.0
User 104: Precision@10 = 0.0
User 105: Precision@10 = 0.0
User 106: Precision@10 = 0.0
User 107: Precision@10 = 0.0
User 108: Precision@10 = 0.0
User 109: Precision@10 = 0.0
User 110: Precision@10 = 0.0
User 111: Precision@10 = 0.0
User 112: Precision@10 = 0.0
User 113: Precision@10 = 0.0
User 114: Precision@10 = 0.0
User 115: Precision@10 = 0.0
User 116: Precision@10 = 0.0
User 117: Precision@10 = 0.0
User 118: Precision@10 = 0.0
User 119: Precision@10 = 0.0
User 120: Precision@10 = 0.0
User 121: Precision@10 = 0.0
User 122: Precision@10 = 0.0
User 123: Precision@10 = 0.0
User 124: Precision@10 = 0.0
User 125: Precision@10 = 0.0
User 126: Precision@10 = 0.0
User 127: Precision@10 = 0.0
User 128: Precision@10 = 0.0
User 129: Precision@10 = 0.0
User 130: Precision@10 = 0.0
User 131: Precision@10 = 0.0
User 132: Precision@10 = 0.0
User 133: Precision@10 = 0.1
User 134: Precision@10 = 0.0
User 135: Precision@10 = 0.0
User 136: Precision@10 = 0.0
User 137: Precision@10 = 0.0
User 138: Precision@10 = 0.1
User 139: Precision@10 = 0.0
User 140: Precision@10 = 0.0
User 141: Precision@10 = 0.0
User 142: Precision@10 = 0.0
User 143: Precision@10 = 0.0
User 144: Precision@10 = 0.0
User 145: Precision@10 = 0.0
User 146: Precision@10 = 0.0
User 147: Precision@10 = 0.0
User 148: Precision@10 = 0.0
User 149: Precision@10 = 0.1
User 150: Precision@10 = 0.0
User 151: Precision@10 = 0.0
User 152: Precision@10 = 0.0
User 153: Precision@10 = 0.0
User 154: Precision@10 = 0.0
User 155: Precision@10 = 0.0
User 156: Precision@10 = 0.0
User 157: Precision@10 = 0.0
User 158: Precision@10 = 0.0
User 159: Precision@10 = 0.0
User 160: Precision@10 = 0.0
User 161: Precision@10 = 0.0
User 162: Precision@10 = 0.0
User 163: Precision@10 = 0.0
User 164: Precision@10 = 0.0
User 165: Precision@10 = 0.1
User 166: Precision@10 = 0.0
User 167: Precision@10 = 0.0
User 168: Precision@10 = 0.0
User 169: Precision@10 = 0.0
User 170: Precision@10 = 0.0
User 171: Precision@10 = 0.0
User 172: Precision@10 = 0.0
User 173: Precision@10 = 0.0
User 174: Precision@10 = 0.0
User 175: Precision@10 = 0.0
User 176: Precision@10 = 0.0
User 177: Precision@10 = 0.0
User 178: Precision@10 = 0.0
User 179: Precision@10 = 0.0
User 180: Precision@10 = 0.0
User 181: Precision@10 = 0.0
User 182: Precision@10 = 0.0
User 183: Precision@10 = 0.0
User 184: Precision@10 = 0.0
User 185: Precision@10 = 0.0
User 186: Precision@10 = 0.0
User 187: Precision@10 = 0.0
User 188: Precision@10 = 0.0
User 189: Precision@10 = 0.0
User 190: Precision@10 = 0.0
User 191: Precision@10 = 0.0
User 192: Precision@10 = 0.0
User 193: Precision@10 = 0.0
User 194: Precision@10 = 0.0
User 195: Precision@10 = 0.0
User 196: Precision@10 = 0.0
User 197: Precision@10 = 0.0
User 198: Precision@10 = 0.0
User 199: Precision@10 = 0.0
User 200: Precision@10 = 0.1
User 201: Precision@10 = 0.0
User 202: Precision@10 = 0.0
User 203: Precision@10 = 0.0
User 204: Precision@10 = 0.0
User 205: Precision@10 = 0.0
User 206: Precision@10 = 0.0
User 207: Precision@10 = 0.1
User 208: Precision@10 = 0.0
User 209: Precision@10 = 0.0
User 210: Precision@10 = 0.0
User 211: Precision@10 = 0.0
User 212: Precision@10 = 0.0
User 213: Precision@10 = 0.1
User 214: Precision@10 = 0.0
User 215: Precision@10 = 0.0
User 216: Precision@10 = 0.0
User 217: Precision@10 = 0.0
User 218: Precision@10 = 0.0
User 219: Precision@10 = 0.0
User 220: Precision@10 = 0.1
User 221: Precision@10 = 0.0
User 222: Precision@10 = 0.0
User 223: Precision@10 = 0.0
User 224: Precision@10 = 0.0
User 225: Precision@10 = 0.0
User 226: Precision@10 = 0.0
User 227: Precision@10 = 0.0
User 228: Precision@10 = 0.0
User 229: Precision@10 = 0.0
User 230: Precision@10 = 0.0
User 231: Precision@10 = 0.0
User 232: Precision@10 = 0.0
User 233: Precision@10 = 0.0
User 234: Precision@10 = 0.0
User 235: Precision@10 = 0.0
User 236: Precision@10 = 0.0
User 237: Precision@10 = 0.0
User 238: Precision@10 = 0.0
User 239: Precision@10 = 0.0
User 240: Precision@10 = 0.0
User 241: Precision@10 = 0.0
User 242: Precision@10 = 0.0
User 243: Precision@10 = 0.0
User 244: Precision@10 = 0.0
User 245: Precision@10 = 0.0
User 246: Precision@10 = 0.0
User 247: Precision@10 = 0.0
User 248: Precision@10 = 0.0
User 249: Precision@10 = 0.0
User 250: Precision@10 = 0.0
User 251: Precision@10 = 0.0
User 252: Precision@10 = 0.0
User 253: Precision@10 = 0.0
User 254: Precision@10 = 0.0
User 255: Precision@10 = 0.0
User 256: Precision@10 = 0.0
User 257: Precision@10 = 0.0
User 258: Precision@10 = 0.0
User 259: Precision@10 = 0.0
User 260: Precision@10 = 0.0
User 261: Precision@10 = 0.0
User 262: Precision@10 = 0.3
User 263: Precision@10 = 0.0
User 264: Precision@10 = 0.0
User 265: Precision@10 = 0.0
User 266: Precision@10 = 0.0
User 267: Precision@10 = 0.0
User 268: Precision@10 = 0.0
User 269: Precision@10 = 0.0
User 270: Precision@10 = 0.0
User 271: Precision@10 = 0.0
User 272: Precision@10 = 0.0
User 273: Precision@10 = 0.0
User 274: Precision@10 = 0.0
User 275: Precision@10 = 0.0
User 276: Precision@10 = 0.0
User 277: Precision@10 = 0.0
User 278: Precision@10 = 0.0
User 279: Precision@10 = 0.0
User 280: Precision@10 = 0.0
User 281: Precision@10 = 0.0
User 282: Precision@10 = 0.0
User 283: Precision@10 = 0.0
User 284: Precision@10 = 0.0
User 285: Precision@10 = 0.0
User 286: Precision@10 = 0.0
User 287: Precision@10 = 0.0
User 288: Precision@10 = 0.0
User 289: Precision@10 = 0.0
User 290: Precision@10 = 0.0
User 291: Precision@10 = 0.0
User 292: Precision@10 = 0.0
User 293: Precision@10 = 0.0
User 294: Precision@10 = 0.0
User 295: Precision@10 = 0.0
User 296: Precision@10 = 0.0
User 297: Precision@10 = 0.0
User 298: Precision@10 = 0.0
User 299: Precision@10 = 0.0
User 300: Precision@10 = 0.0
User 301: Precision@10 = 0.0
User 302: Precision@10 = 0.0
User 303: Precision@10 = 0.0
User 304: Precision@10 = 0.0
User 305: Precision@10 = 0.1
User 306: Precision@10 = 0.0
User 307: Precision@10 = 0.0
User 308: Precision@10 = 0.0
User 309: Precision@10 = 0.0
User 310: Precision@10 = 0.0
User 311: Precision@10 = 0.0
User 312: Precision@10 = 0.1
User 313: Precision@10 = 0.0
User 314: Precision@10 = 0.0
User 315: Precision@10 = 0.0
User 316: Precision@10 = 0.0
User 317: Precision@10 = 0.0
User 318: Precision@10 = 0.0
User 319: Precision@10 = 0.0
User 320: Precision@10 = 0.0
User 321: Precision@10 = 0.0
User 322: Precision@10 = 0.0
User 323: Precision@10 = 0.0
User 324: Precision@10 = 0.0
User 325: Precision@10 = 0.0
User 326: Precision@10 = 0.0
User 327: Precision@10 = 0.0
User 328: Precision@10 = 0.0
User 329: Precision@10 = 0.0
User 330: Precision@10 = 0.0
User 331: Precision@10 = 0.0
User 332: Precision@10 = 0.0
User 333: Precision@10 = 0.0
User 334: Precision@10 = 0.0
User 335: Precision@10 = 0.0
User 336: Precision@10 = 0.0
User 337: Precision@10 = 0.0
User 338: Precision@10 = 0.0
User 339: Precision@10 = 0.0
User 340: Precision@10 = 0.0
User 341: Precision@10 = 0.0
User 342: Precision@10 = 0.0
User 343: Precision@10 = 0.0
User 344: Precision@10 = 0.0
User 345: Precision@10 = 0.0
User 346: Precision@10 = 0.0
User 347: Precision@10 = 0.0
User 348: Precision@10 = 0.0
User 349: Precision@10 = 0.0
User 350: Precision@10 = 0.0
User 351: Precision@10 = 0.0
User 352: Precision@10 = 0.0
User 353: Precision@10 = 0.0
User 354: Precision@10 = 0.0
User 355: Precision@10 = 0.0
User 356: Precision@10 = 0.0
User 357: Precision@10 = 0.0
User 358: Precision@10 = 0.0
User 359: Precision@10 = 0.0
User 360: Precision@10 = 0.0
User 361: Precision@10 = 0.0
User 362: Precision@10 = 0.0
User 363: Precision@10 = 0.0
User 364: Precision@10 = 0.0
User 365: Precision@10 = 0.0
User 366: Precision@10 = 0.0
User 367: Precision@10 = 0.1
User 368: Precision@10 = 0.0
User 369: Precision@10 = 0.0
User 370: Precision@10 = 0.0
User 371: Precision@10 = 0.0
User 372: Precision@10 = 0.0
User 373: Precision@10 = 0.0
User 374: Precision@10 = 0.0
User 375: Precision@10 = 0.0
User 376: Precision@10 = 0.0
User 377: Precision@10 = 0.0
User 378: Precision@10 = 0.0
User 379: Precision@10 = 0.0
User 380: Precision@10 = 0.0
User 381: Precision@10 = 0.0
User 382: Precision@10 = 0.0
User 383: Precision@10 = 0.0
User 384: Precision@10 = 0.0
User 385: Precision@10 = 0.0
User 386: Precision@10 = 0.0
User 387: Precision@10 = 0.0
User 388: Precision@10 = 0.0
User 389: Precision@10 = 0.0
User 390: Precision@10 = 0.0
User 391: Precision@10 = 0.0
User 392: Precision@10 = 0.0
User 393: Precision@10 = 0.0
User 394: Precision@10 = 0.0
User 395: Precision@10 = 0.0
User 396: Precision@10 = 0.0
User 397: Precision@10 = 0.0
User 398: Precision@10 = 0.0
User 399: Precision@10 = 0.0
User 400: Precision@10 = 0.0
User 401: Precision@10 = 0.0
User 402: Precision@10 = 0.0
User 403: Precision@10 = 0.0
User 404: Precision@10 = 0.0
User 405: Precision@10 = 0.0
User 406: Precision@10 = 0.0
User 407: Precision@10 = 0.0
User 408: Precision@10 = 0.0
User 409: Precision@10 = 0.0
User 410: Precision@10 = 0.0
User 411: Precision@10 = 0.0
User 412: Precision@10 = 0.0
User 413: Precision@10 = 0.0
User 414: Precision@10 = 0.0
User 415: Precision@10 = 0.0
User 416: Precision@10 = 0.0
User 417: Precision@10 = 0.0
User 418: Precision@10 = 0.0
User 419: Precision@10 = 0.0
User 420: Precision@10 = 0.0
User 421: Precision@10 = 0.0
User 422: Precision@10 = 0.0
User 423: Precision@10 = 0.0
User 424: Precision@10 = 0.0
User 425: Precision@10 = 0.1
User 426: Precision@10 = 0.3
User 427: Precision@10 = 0.0
User 428: Precision@10 = 0.1
User 429: Precision@10 = 0.0
User 430: Precision@10 = 0.0
User 431: Precision@10 = 0.0
User 432: Precision@10 = 0.0
User 433: Precision@10 = 0.0
User 434: Precision@10 = 0.0
User 435: Precision@10 = 0.0
User 436: Precision@10 = 0.0
User 437: Precision@10 = 0.0
User 438: Precision@10 = 0.0
User 439: Precision@10 = 0.0
User 440: Precision@10 = 0.0
User 441: Precision@10 = 0.0
User 442: Precision@10 = 0.0
User 443: Precision@10 = 0.0
User 444: Precision@10 = 0.0
User 445: Precision@10 = 0.0
User 446: Precision@10 = 0.0
User 447: Precision@10 = 0.0
User 448: Precision@10 = 0.0
User 449: Precision@10 = 0.0
User 450: Precision@10 = 0.0
User 451: Precision@10 = 0.0
User 452: Precision@10 = 0.0
User 453: Precision@10 = 0.0
User 454: Precision@10 = 0.0
User 455: Precision@10 = 0.0
User 456: Precision@10 = 0.0
User 457: Precision@10 = 0.2
User 458: Precision@10 = 0.0
User 459: Precision@10 = 0.0
User 460: Precision@10 = 0.0
User 461: Precision@10 = 0.0
User 462: Precision@10 = 0.0
User 463: Precision@10 = 0.0
User 464: Precision@10 = 0.0
User 465: Precision@10 = 0.0
User 466: Precision@10 = 0.0
User 467: Precision@10 = 0.0
User 468: Precision@10 = 0.2
User 469: Precision@10 = 0.0
User 470: Precision@10 = 0.0
User 471: Precision@10 = 0.0
User 472: Precision@10 = 0.1
User 473: Precision@10 = 0.0
User 474: Precision@10 = 0.0
User 475: Precision@10 = 0.4
User 476: Precision@10 = 0.0
User 477: Precision@10 = 0.0
User 478: Precision@10 = 0.0
User 479: Precision@10 = 0.0
User 480: Precision@10 = 0.0
User 481: Precision@10 = 0.0
User 482: Precision@10 = 0.0
User 483: Precision@10 = 0.0
User 484: Precision@10 = 0.0
User 485: Precision@10 = 0.0
User 486: Precision@10 = 0.0
User 487: Precision@10 = 0.0
User 488: Precision@10 = 0.0
User 489: Precision@10 = 0.0
User 490: Precision@10 = 0.0
User 491: Precision@10 = 0.0
User 492: Precision@10 = 0.0
User 493: Precision@10 = 0.0
User 494: Precision@10 = 0.0
User 495: Precision@10 = 0.0
User 496: Precision@10 = 0.0
User 497: Precision@10 = 0.0
User 498: Precision@10 = 0.0
User 499: Precision@10 = 0.0
User 500: Precision@10 = 0.0
User 501: Precision@10 = 0.0
User 502: Precision@10 = 0.0
User 503: Precision@10 = 0.0
User 504: Precision@10 = 0.0
User 505: Precision@10 = 0.0
User 506: Precision@10 = 0.0
User 507: Precision@10 = 0.0
User 508: Precision@10 = 0.0
User 509: Precision@10 = 0.0
User 510: Precision@10 = 0.0
User 511: Precision@10 = 0.0
User 512: Precision@10 = 0.0
User 513: Precision@10 = 0.0
User 514: Precision@10 = 0.0
User 515: Precision@10 = 0.0
User 516: Precision@10 = 0.0
User 517: Precision@10 = 0.0
User 518: Precision@10 = 0.0
User 519: Precision@10 = 0.0
User 520: Precision@10 = 0.0
User 521: Precision@10 = 0.0
User 522: Precision@10 = 0.0
User 523: Precision@10 = 0.0
User 524: Precision@10 = 0.0
User 525: Precision@10 = 0.0
User 526: Precision@10 = 0.0
User 527: Precision@10 = 0.0
User 528: Precision@10 = 0.0
User 529: Precision@10 = 0.0
User 530: Precision@10 = 0.0
User 531: Precision@10 = 0.0
User 532: Precision@10 = 0.0
User 533: Precision@10 = 0.0
User 534: Precision@10 = 0.0
User 535: Precision@10 = 0.0
User 536: Precision@10 = 0.0
User 537: Precision@10 = 0.0
User 538: Precision@10 = 0.0
User 539: Precision@10 = 0.0
User 540: Precision@10 = 0.0
User 541: Precision@10 = 0.0
User 542: Precision@10 = 0.0
User 543: Precision@10 = 0.0
User 544: Precision@10 = 0.0
User 545: Precision@10 = 0.0
User 546: Precision@10 = 0.0
User 547: Precision@10 = 0.1
User 548: Precision@10 = 0.0
User 549: Precision@10 = 0.0
User 550: Precision@10 = 0.0
User 551: Precision@10 = 0.0
User 552: Precision@10 = 0.0
User 553: Precision@10 = 0.2
User 554: Precision@10 = 0.0
User 555: Precision@10 = 0.1
User 556: Precision@10 = 0.0
User 557: Precision@10 = 0.0
User 558: Precision@10 = 0.0
User 559: Precision@10 = 0.0
User 560: Precision@10 = 0.0
User 561: Precision@10 = 0.0
User 562: Precision@10 = 0.0
User 563: Precision@10 = 0.0
User 564: Precision@10 = 0.0
User 565: Precision@10 = 0.0
User 566: Precision@10 = 0.0
User 567: Precision@10 = 0.0
User 568: Precision@10 = 0.0
User 569: Precision@10 = 0.0
User 570: Precision@10 = 0.0
User 571: Precision@10 = 0.0
User 572: Precision@10 = 0.0
User 573: Precision@10 = 0.0
User 574: Precision@10 = 0.0
User 575: Precision@10 = 0.0
User 576: Precision@10 = 0.0
User 577: Precision@10 = 0.0
User 578: Precision@10 = 0.1
User 579: Precision@10 = 0.1
User 580: Precision@10 = 0.0
User 581: Precision@10 = 0.0
User 582: Precision@10 = 0.0
User 583: Precision@10 = 0.0
User 584: Precision@10 = 0.0
User 585: Precision@10 = 0.0
User 586: Precision@10 = 0.2
User 587: Precision@10 = 0.0
User 588: Precision@10 = 0.0
User 589: Precision@10 = 0.0
User 590: Precision@10 = 0.0
User 591: Precision@10 = 0.0
User 592: Precision@10 = 0.0
User 593: Precision@10 = 0.0
User 594: Precision@10 = 0.0
User 595: Precision@10 = 0.0
User 596: Precision@10 = 0.0
User 597: Precision@10 = 0.0
User 598: Precision@10 = 0.0
User 599: Precision@10 = 0.0
User 600: Precision@10 = 0.0
User 601: Precision@10 = 0.0
User 602: Precision@10 = 0.0
User 603: Precision@10 = 0.0
User 604: Precision@10 = 0.0
User 605: Precision@10 = 0.0
User 606: Precision@10 = 0.0
User 607: Precision@10 = 0.0
User 608: Precision@10 = 0.0
User 609: Precision@10 = 0.0
User 610: Precision@10 = 0.0
User 611: Precision@10 = 0.0
User 612: Precision@10 = 0.0
User 613: Precision@10 = 0.0
User 614: Precision@10 = 0.0
User 615: Precision@10 = 0.0
User 616: Precision@10 = 0.0
User 617: Precision@10 = 0.0
User 618: Precision@10 = 0.0
User 619: Precision@10 = 0.0
User 620: Precision@10 = 0.0
User 621: Precision@10 = 0.0
User 622: Precision@10 = 0.0
User 623: Precision@10 = 0.0
User 624: Precision@10 = 0.1
User 625: Precision@10 = 0.0
User 626: Precision@10 = 0.0
User 627: Precision@10 = 0.0
User 628: Precision@10 = 0.0
User 629: Precision@10 = 0.1
User 630: Precision@10 = 0.0
User 631: Precision@10 = 0.0
User 632: Precision@10 = 0.0
User 633: Precision@10 = 0.0
User 634: Precision@10 = 0.0
User 635: Precision@10 = 0.0
User 636: Precision@10 = 0.0
User 637: Precision@10 = 0.0
User 638: Precision@10 = 0.0
User 639: Precision@10 = 0.0
User 640: Precision@10 = 0.0
User 641: Precision@10 = 0.0
User 642: Precision@10 = 0.0
User 643: Precision@10 = 0.0
User 644: Precision@10 = 0.0
User 645: Precision@10 = 0.0
User 646: Precision@10 = 0.0
User 647: Precision@10 = 0.0
User 648: Precision@10 = 0.0
User 649: Precision@10 = 0.0
User 650: Precision@10 = 0.0
User 651: Precision@10 = 0.0
User 652: Precision@10 = 0.0
User 653: Precision@10 = 0.0
User 654: Precision@10 = 0.0
User 655: Precision@10 = 0.0
User 656: Precision@10 = 0.0
User 657: Precision@10 = 0.0
User 658: Precision@10 = 0.0
User 659: Precision@10 = 0.0
User 660: Precision@10 = 0.0
User 661: Precision@10 = 0.0
User 662: Precision@10 = 0.0
User 663: Precision@10 = 0.0
User 664: Precision@10 = 0.0
User 665: Precision@10 = 0.0
User 666: Precision@10 = 0.0
User 667: Precision@10 = 0.0
User 668: Precision@10 = 0.0
User 669: Precision@10 = 0.0
User 670: Precision@10 = 0.0
User 671: Precision@10 = 0.0

In [ ]:
mrrScores = []
for i in range(len(userItemBoolean)):
    rank = 0.0
    for j in range(len(userItemBoolean[i])):
        if userItemBoolean[i][j]:
            rank = 1.0 / (j + 1)
            break
    mrrScores.append(rank)

meanMrr = np.mean(mrrScores)
print(f"Mean Reciprocal Rank (MRR): {meanMrr}")

Mean Reciprocal Rank (MRR): 0.29001479034948874

## References

https://medium.com/data-science/recommendation-system-matrix-factorization-d61978660b4b
https://www.geeksforgeeks.org/python/python-mean-squared-error/
https://www.evidentlyai.com/ranking-metrics/precision-recall-at-k
https://www.geeksforgeeks.org/nlp/evaluation-metrics-for-retrieval-augmented-generation-rag-systems/